/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq;


import com.github.gwiman.mini_mes_backend.jooq.tables.CodeGroup;
import com.github.gwiman.mini_mes_backend.jooq.tables.CommonCode;
import com.github.gwiman.mini_mes_backend.jooq.tables.Employee;
import com.github.gwiman.mini_mes_backend.jooq.tables.EventPublication;
import com.github.gwiman.mini_mes_backend.jooq.tables.Item;
import com.github.gwiman.mini_mes_backend.jooq.tables.Partner;
import com.github.gwiman.mini_mes_backend.jooq.tables.Process;
import com.github.gwiman.mini_mes_backend.jooq.tables.Quote;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrder;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrderLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Users;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.CodeGroupRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.CommonCodeRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.EmployeeRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.EventPublicationRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ItemRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PartnerRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ProcessRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CodeGroupRecord> CODE_GROUP_PKEY = Internal.createUniqueKey(CodeGroup.CODE_GROUP, DSL.name("code_group_pkey"), new TableField[] { CodeGroup.CODE_GROUP.ID }, true);
    public static final UniqueKey<CodeGroupRecord> UKANYWI85GA0C2V0JC8Q8UEKWM5 = Internal.createUniqueKey(CodeGroup.CODE_GROUP, DSL.name("ukanywi85ga0c2v0jc8q8uekwm5"), new TableField[] { CodeGroup.CODE_GROUP.GROUP_CODE }, true);
    public static final UniqueKey<CommonCodeRecord> COMMON_CODE_PKEY = Internal.createUniqueKey(CommonCode.COMMON_CODE, DSL.name("common_code_pkey"), new TableField[] { CommonCode.COMMON_CODE.ID }, true);
    public static final UniqueKey<EmployeeRecord> EMPLOYEE_PKEY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("employee_pkey"), new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final UniqueKey<EmployeeRecord> UKNBYIVU8QGMX0R7WTBPLF01GF8 = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("uknbyivu8qgmx0r7wtbplf01gf8"), new TableField[] { Employee.EMPLOYEE.CODE }, true);
    public static final UniqueKey<EventPublicationRecord> EVENT_PUBLICATION_PKEY = Internal.createUniqueKey(EventPublication.EVENT_PUBLICATION, DSL.name("event_publication_pkey"), new TableField[] { EventPublication.EVENT_PUBLICATION.ID }, true);
    public static final UniqueKey<ItemRecord> ITEM_PKEY = Internal.createUniqueKey(Item.ITEM, DSL.name("item_pkey"), new TableField[] { Item.ITEM.ID }, true);
    public static final UniqueKey<ItemRecord> UK6CGOGDARKQ48DLG1LBNV4Q1OQ = Internal.createUniqueKey(Item.ITEM, DSL.name("uk6cgogdarkq48dlg1lbnv4q1oq"), new TableField[] { Item.ITEM.CODE }, true);
    public static final UniqueKey<PartnerRecord> PARTNER_PKEY = Internal.createUniqueKey(Partner.PARTNER, DSL.name("partner_pkey"), new TableField[] { Partner.PARTNER.ID }, true);
    public static final UniqueKey<PartnerRecord> UKFIV57HN037FRDWMYQNX8MKQ9N = Internal.createUniqueKey(Partner.PARTNER, DSL.name("ukfiv57hn037frdwmyqnx8mkq9n"), new TableField[] { Partner.PARTNER.CODE }, true);
    public static final UniqueKey<ProcessRecord> PROCESS_PKEY = Internal.createUniqueKey(Process.PROCESS, DSL.name("process_pkey"), new TableField[] { Process.PROCESS.ID }, true);
    public static final UniqueKey<ProcessRecord> UK5HLDOWCQY94Y1GWBPNYTOFX4H = Internal.createUniqueKey(Process.PROCESS, DSL.name("uk5hldowcqy94y1gwbpnytofx4h"), new TableField[] { Process.PROCESS.CODE }, true);
    public static final UniqueKey<QuoteRecord> QUOTE_PKEY = Internal.createUniqueKey(Quote.QUOTE, DSL.name("quote_pkey"), new TableField[] { Quote.QUOTE.ID }, true);
    public static final UniqueKey<QuoteRecord> UKC6L8KA84HB9DFDG5PKHT3FA79 = Internal.createUniqueKey(Quote.QUOTE, DSL.name("ukc6l8ka84hb9dfdg5pkht3fa79"), new TableField[] { Quote.QUOTE.QUOTE_NUMBER }, true);
    public static final UniqueKey<QuoteLineRecord> QUOTE_LINE_PKEY = Internal.createUniqueKey(QuoteLine.QUOTE_LINE, DSL.name("quote_line_pkey"), new TableField[] { QuoteLine.QUOTE_LINE.ID }, true);
    public static final UniqueKey<SalesOrderRecord> SALES_ORDER_PKEY = Internal.createUniqueKey(SalesOrder.SALES_ORDER, DSL.name("sales_order_pkey"), new TableField[] { SalesOrder.SALES_ORDER.ID }, true);
    public static final UniqueKey<SalesOrderRecord> UKITDRI3LNOQU7YV0W5LYUC5TOS = Internal.createUniqueKey(SalesOrder.SALES_ORDER, DSL.name("ukitdri3lnoqu7yv0w5lyuc5tos"), new TableField[] { SalesOrder.SALES_ORDER.ORDER_NUMBER }, true);
    public static final UniqueKey<SalesOrderLineRecord> SALES_ORDER_LINE_PKEY = Internal.createUniqueKey(SalesOrderLine.SALES_ORDER_LINE, DSL.name("sales_order_line_pkey"), new TableField[] { SalesOrderLine.SALES_ORDER_LINE.ID }, true);
    public static final UniqueKey<UsersRecord> UKD1S31G1A7ILRA77M65XMKA3EI = Internal.createUniqueKey(Users.USERS, DSL.name("ukd1s31g1a7ilra77m65xmka3ei"), new TableField[] { Users.USERS.EMPLOYEE_ID }, true);
    public static final UniqueKey<UsersRecord> UKR43AF9AP4EDM43MMTQ01ODDJ6 = Internal.createUniqueKey(Users.USERS, DSL.name("ukr43af9ap4edm43mmtq01oddj6"), new TableField[] { Users.USERS.USERNAME }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<QuoteRecord, PartnerRecord> QUOTE__FK9ALFG10RCMMPSCETID6LB5OOT = Internal.createForeignKey(Quote.QUOTE, DSL.name("fk9alfg10rcmmpscetid6lb5oot"), new TableField[] { Quote.QUOTE.PARTNER_ID }, Keys.PARTNER_PKEY, new TableField[] { Partner.PARTNER.ID }, true);
    public static final ForeignKey<QuoteRecord, EmployeeRecord> QUOTE__FKODPO7A1F6TCCW81W7G8845R8F = Internal.createForeignKey(Quote.QUOTE, DSL.name("fkodpo7a1f6tccw81w7g8845r8f"), new TableField[] { Quote.QUOTE.EMPLOYEE_ID }, Keys.EMPLOYEE_PKEY, new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final ForeignKey<QuoteLineRecord, ItemRecord> QUOTE_LINE__FKJ26RAJPBGQ93FD2VDRP775T8A = Internal.createForeignKey(QuoteLine.QUOTE_LINE, DSL.name("fkj26rajpbgq93fd2vdrp775t8a"), new TableField[] { QuoteLine.QUOTE_LINE.ITEM_ID }, Keys.ITEM_PKEY, new TableField[] { Item.ITEM.ID }, true);
    public static final ForeignKey<QuoteLineRecord, QuoteRecord> QUOTE_LINE__FKNBXR28WOT0665O7O2FGY4H0XR = Internal.createForeignKey(QuoteLine.QUOTE_LINE, DSL.name("fknbxr28wot0665o7o2fgy4h0xr"), new TableField[] { QuoteLine.QUOTE_LINE.QUOTE_ID }, Keys.QUOTE_PKEY, new TableField[] { Quote.QUOTE.ID }, true);
    public static final ForeignKey<SalesOrderRecord, QuoteRecord> SALES_ORDER__FK8P31F0RWK0HB56I1K9XOSL2VY = Internal.createForeignKey(SalesOrder.SALES_ORDER, DSL.name("fk8p31f0rwk0hb56i1k9xosl2vy"), new TableField[] { SalesOrder.SALES_ORDER.QUOTE_ID }, Keys.QUOTE_PKEY, new TableField[] { Quote.QUOTE.ID }, true);
    public static final ForeignKey<SalesOrderRecord, EmployeeRecord> SALES_ORDER__FKLBFR3ECCAMEAMC9LWELBG7U7L = Internal.createForeignKey(SalesOrder.SALES_ORDER, DSL.name("fklbfr3eccameamc9lwelbg7u7l"), new TableField[] { SalesOrder.SALES_ORDER.EMPLOYEE_ID }, Keys.EMPLOYEE_PKEY, new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final ForeignKey<SalesOrderRecord, PartnerRecord> SALES_ORDER__FKP3PUH9SDRFN03H5Q818MM5VH0 = Internal.createForeignKey(SalesOrder.SALES_ORDER, DSL.name("fkp3puh9sdrfn03h5q818mm5vh0"), new TableField[] { SalesOrder.SALES_ORDER.PARTNER_ID }, Keys.PARTNER_PKEY, new TableField[] { Partner.PARTNER.ID }, true);
    public static final ForeignKey<SalesOrderLineRecord, SalesOrderRecord> SALES_ORDER_LINE__FK3HHRMXPWT1CQLNXMTIWPY9WPG = Internal.createForeignKey(SalesOrderLine.SALES_ORDER_LINE, DSL.name("fk3hhrmxpwt1cqlnxmtiwpy9wpg"), new TableField[] { SalesOrderLine.SALES_ORDER_LINE.SALES_ORDER_ID }, Keys.SALES_ORDER_PKEY, new TableField[] { SalesOrder.SALES_ORDER.ID }, true);
    public static final ForeignKey<SalesOrderLineRecord, ItemRecord> SALES_ORDER_LINE__FKSX78NRSMY3OC216VK4KTMY1L9 = Internal.createForeignKey(SalesOrderLine.SALES_ORDER_LINE, DSL.name("fksx78nrsmy3oc216vk4ktmy1l9"), new TableField[] { SalesOrderLine.SALES_ORDER_LINE.ITEM_ID }, Keys.ITEM_PKEY, new TableField[] { Item.ITEM.ID }, true);
}
