/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq;


import com.github.gwiman.mini_mes_backend.jooq.tables.Bom;
import com.github.gwiman.mini_mes_backend.jooq.tables.BomLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.CodeGroup;
import com.github.gwiman.mini_mes_backend.jooq.tables.CommonCode;
import com.github.gwiman.mini_mes_backend.jooq.tables.Employee;
import com.github.gwiman.mini_mes_backend.jooq.tables.EventPublication;
import com.github.gwiman.mini_mes_backend.jooq.tables.GoodsReceipt;
import com.github.gwiman.mini_mes_backend.jooq.tables.GoodsReceiptLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Inventory;
import com.github.gwiman.mini_mes_backend.jooq.tables.InventoryLot;
import com.github.gwiman.mini_mes_backend.jooq.tables.InventoryTx;
import com.github.gwiman.mini_mes_backend.jooq.tables.Item;
import com.github.gwiman.mini_mes_backend.jooq.tables.ItemPrice;
import com.github.gwiman.mini_mes_backend.jooq.tables.Partner;
import com.github.gwiman.mini_mes_backend.jooq.tables.Process;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseOrder;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseOrderLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseRequest;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseRequestLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Quote;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteApproval;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Revenue;
import com.github.gwiman.mini_mes_backend.jooq.tables.RevenueLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Routing;
import com.github.gwiman.mini_mes_backend.jooq.tables.RoutingStep;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrder;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrderLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Shipment;
import com.github.gwiman.mini_mes_backend.jooq.tables.ShipmentLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Users;
import com.github.gwiman.mini_mes_backend.jooq.tables.Warehouse;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.BomLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.BomRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.CodeGroupRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.CommonCodeRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.EmployeeRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.EventPublicationRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.GoodsReceiptLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.GoodsReceiptRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.InventoryLotRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.InventoryRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.InventoryTxRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ItemPriceRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ItemRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PartnerRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ProcessRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseOrderLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseOrderRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseRequestLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseRequestRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteApprovalRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RevenueLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RevenueRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RoutingRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RoutingStepRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ShipmentLineRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ShipmentRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.UsersRecord;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.WarehouseRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BomRecord> BOM_PKEY = Internal.createUniqueKey(Bom.BOM, DSL.name("bom_pkey"), new TableField[] { Bom.BOM.ID }, true);
    public static final UniqueKey<BomRecord> UK_BOM_ITEM_VERSION = Internal.createUniqueKey(Bom.BOM, DSL.name("uk_bom_item_version"), new TableField[] { Bom.BOM.ITEM_ID, Bom.BOM.VERSION_CODE }, true);
    public static final UniqueKey<BomLineRecord> BOM_LINE_PKEY = Internal.createUniqueKey(BomLine.BOM_LINE, DSL.name("bom_line_pkey"), new TableField[] { BomLine.BOM_LINE.ID }, true);
    public static final UniqueKey<CodeGroupRecord> CODE_GROUP_GROUP_CODE_KEY = Internal.createUniqueKey(CodeGroup.CODE_GROUP, DSL.name("code_group_group_code_key"), new TableField[] { CodeGroup.CODE_GROUP.GROUP_CODE }, true);
    public static final UniqueKey<CodeGroupRecord> CODE_GROUP_PKEY = Internal.createUniqueKey(CodeGroup.CODE_GROUP, DSL.name("code_group_pkey"), new TableField[] { CodeGroup.CODE_GROUP.ID }, true);
    public static final UniqueKey<CommonCodeRecord> COMMON_CODE_PKEY = Internal.createUniqueKey(CommonCode.COMMON_CODE, DSL.name("common_code_pkey"), new TableField[] { CommonCode.COMMON_CODE.ID }, true);
    public static final UniqueKey<EmployeeRecord> EMPLOYEE_CODE_KEY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("employee_code_key"), new TableField[] { Employee.EMPLOYEE.CODE }, true);
    public static final UniqueKey<EmployeeRecord> EMPLOYEE_PKEY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("employee_pkey"), new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final UniqueKey<EventPublicationRecord> EVENT_PUBLICATION_PKEY = Internal.createUniqueKey(EventPublication.EVENT_PUBLICATION, DSL.name("event_publication_pkey"), new TableField[] { EventPublication.EVENT_PUBLICATION.ID }, true);
    public static final UniqueKey<GoodsReceiptRecord> GOODS_RECEIPT_PKEY = Internal.createUniqueKey(GoodsReceipt.GOODS_RECEIPT, DSL.name("goods_receipt_pkey"), new TableField[] { GoodsReceipt.GOODS_RECEIPT.ID }, true);
    public static final UniqueKey<GoodsReceiptRecord> GOODS_RECEIPT_RECEIPT_NUMBER_KEY = Internal.createUniqueKey(GoodsReceipt.GOODS_RECEIPT, DSL.name("goods_receipt_receipt_number_key"), new TableField[] { GoodsReceipt.GOODS_RECEIPT.RECEIPT_NUMBER }, true);
    public static final UniqueKey<GoodsReceiptLineRecord> GOODS_RECEIPT_LINE_PKEY = Internal.createUniqueKey(GoodsReceiptLine.GOODS_RECEIPT_LINE, DSL.name("goods_receipt_line_pkey"), new TableField[] { GoodsReceiptLine.GOODS_RECEIPT_LINE.ID }, true);
    public static final UniqueKey<InventoryRecord> INVENTORY_PKEY = Internal.createUniqueKey(Inventory.INVENTORY, DSL.name("inventory_pkey"), new TableField[] { Inventory.INVENTORY.ID }, true);
    public static final UniqueKey<InventoryRecord> INVENTORY_WAREHOUSE_ID_ITEM_ID_KEY = Internal.createUniqueKey(Inventory.INVENTORY, DSL.name("inventory_warehouse_id_item_id_key"), new TableField[] { Inventory.INVENTORY.WAREHOUSE_ID, Inventory.INVENTORY.ITEM_ID }, true);
    public static final UniqueKey<InventoryLotRecord> INVENTORY_LOT_PKEY = Internal.createUniqueKey(InventoryLot.INVENTORY_LOT, DSL.name("inventory_lot_pkey"), new TableField[] { InventoryLot.INVENTORY_LOT.ID }, true);
    public static final UniqueKey<InventoryLotRecord> INVENTORY_LOT_WAREHOUSE_ID_ITEM_ID_LOT_NO_KEY = Internal.createUniqueKey(InventoryLot.INVENTORY_LOT, DSL.name("inventory_lot_warehouse_id_item_id_lot_no_key"), new TableField[] { InventoryLot.INVENTORY_LOT.WAREHOUSE_ID, InventoryLot.INVENTORY_LOT.ITEM_ID, InventoryLot.INVENTORY_LOT.LOT_NO }, true);
    public static final UniqueKey<InventoryTxRecord> INVENTORY_TX_PKEY = Internal.createUniqueKey(InventoryTx.INVENTORY_TX, DSL.name("inventory_tx_pkey"), new TableField[] { InventoryTx.INVENTORY_TX.ID }, true);
    public static final UniqueKey<ItemRecord> ITEM_CODE_KEY = Internal.createUniqueKey(Item.ITEM, DSL.name("item_code_key"), new TableField[] { Item.ITEM.CODE }, true);
    public static final UniqueKey<ItemRecord> ITEM_PKEY = Internal.createUniqueKey(Item.ITEM, DSL.name("item_pkey"), new TableField[] { Item.ITEM.ID }, true);
    public static final UniqueKey<ItemPriceRecord> ITEM_PRICE_ITEM_ID_KEY = Internal.createUniqueKey(ItemPrice.ITEM_PRICE, DSL.name("item_price_item_id_key"), new TableField[] { ItemPrice.ITEM_PRICE.ITEM_ID }, true);
    public static final UniqueKey<ItemPriceRecord> ITEM_PRICE_PKEY = Internal.createUniqueKey(ItemPrice.ITEM_PRICE, DSL.name("item_price_pkey"), new TableField[] { ItemPrice.ITEM_PRICE.ID }, true);
    public static final UniqueKey<PartnerRecord> PARTNER_CODE_KEY = Internal.createUniqueKey(Partner.PARTNER, DSL.name("partner_code_key"), new TableField[] { Partner.PARTNER.CODE }, true);
    public static final UniqueKey<PartnerRecord> PARTNER_PKEY = Internal.createUniqueKey(Partner.PARTNER, DSL.name("partner_pkey"), new TableField[] { Partner.PARTNER.ID }, true);
    public static final UniqueKey<ProcessRecord> PROCESS_CODE_KEY = Internal.createUniqueKey(Process.PROCESS, DSL.name("process_code_key"), new TableField[] { Process.PROCESS.CODE }, true);
    public static final UniqueKey<ProcessRecord> PROCESS_PKEY = Internal.createUniqueKey(Process.PROCESS, DSL.name("process_pkey"), new TableField[] { Process.PROCESS.ID }, true);
    public static final UniqueKey<PurchaseOrderRecord> PURCHASE_ORDER_ORDER_NUMBER_KEY = Internal.createUniqueKey(PurchaseOrder.PURCHASE_ORDER, DSL.name("purchase_order_order_number_key"), new TableField[] { PurchaseOrder.PURCHASE_ORDER.ORDER_NUMBER }, true);
    public static final UniqueKey<PurchaseOrderRecord> PURCHASE_ORDER_PKEY = Internal.createUniqueKey(PurchaseOrder.PURCHASE_ORDER, DSL.name("purchase_order_pkey"), new TableField[] { PurchaseOrder.PURCHASE_ORDER.ID }, true);
    public static final UniqueKey<PurchaseOrderLineRecord> PURCHASE_ORDER_LINE_PKEY = Internal.createUniqueKey(PurchaseOrderLine.PURCHASE_ORDER_LINE, DSL.name("purchase_order_line_pkey"), new TableField[] { PurchaseOrderLine.PURCHASE_ORDER_LINE.ID }, true);
    public static final UniqueKey<PurchaseRequestRecord> PURCHASE_REQUEST_PKEY = Internal.createUniqueKey(PurchaseRequest.PURCHASE_REQUEST, DSL.name("purchase_request_pkey"), new TableField[] { PurchaseRequest.PURCHASE_REQUEST.ID }, true);
    public static final UniqueKey<PurchaseRequestRecord> PURCHASE_REQUEST_REQUEST_NUMBER_KEY = Internal.createUniqueKey(PurchaseRequest.PURCHASE_REQUEST, DSL.name("purchase_request_request_number_key"), new TableField[] { PurchaseRequest.PURCHASE_REQUEST.REQUEST_NUMBER }, true);
    public static final UniqueKey<PurchaseRequestLineRecord> PURCHASE_REQUEST_LINE_PKEY = Internal.createUniqueKey(PurchaseRequestLine.PURCHASE_REQUEST_LINE, DSL.name("purchase_request_line_pkey"), new TableField[] { PurchaseRequestLine.PURCHASE_REQUEST_LINE.ID }, true);
    public static final UniqueKey<QuoteRecord> QUOTE_PKEY = Internal.createUniqueKey(Quote.QUOTE, DSL.name("quote_pkey"), new TableField[] { Quote.QUOTE.ID }, true);
    public static final UniqueKey<QuoteRecord> QUOTE_QUOTE_NUMBER_KEY = Internal.createUniqueKey(Quote.QUOTE, DSL.name("quote_quote_number_key"), new TableField[] { Quote.QUOTE.QUOTE_NUMBER }, true);
    public static final UniqueKey<QuoteApprovalRecord> QUOTE_APPROVAL_PKEY = Internal.createUniqueKey(QuoteApproval.QUOTE_APPROVAL, DSL.name("quote_approval_pkey"), new TableField[] { QuoteApproval.QUOTE_APPROVAL.ID }, true);
    public static final UniqueKey<QuoteLineRecord> QUOTE_LINE_PKEY = Internal.createUniqueKey(QuoteLine.QUOTE_LINE, DSL.name("quote_line_pkey"), new TableField[] { QuoteLine.QUOTE_LINE.ID }, true);
    public static final UniqueKey<RevenueRecord> REVENUE_PKEY = Internal.createUniqueKey(Revenue.REVENUE, DSL.name("revenue_pkey"), new TableField[] { Revenue.REVENUE.ID }, true);
    public static final UniqueKey<RevenueRecord> REVENUE_REVENUE_NUMBER_KEY = Internal.createUniqueKey(Revenue.REVENUE, DSL.name("revenue_revenue_number_key"), new TableField[] { Revenue.REVENUE.REVENUE_NUMBER }, true);
    public static final UniqueKey<RevenueLineRecord> REVENUE_LINE_PKEY = Internal.createUniqueKey(RevenueLine.REVENUE_LINE, DSL.name("revenue_line_pkey"), new TableField[] { RevenueLine.REVENUE_LINE.ID }, true);
    public static final UniqueKey<RoutingRecord> ROUTING_BOM_ID_KEY = Internal.createUniqueKey(Routing.ROUTING, DSL.name("routing_bom_id_key"), new TableField[] { Routing.ROUTING.BOM_ID }, true);
    public static final UniqueKey<RoutingRecord> ROUTING_PKEY = Internal.createUniqueKey(Routing.ROUTING, DSL.name("routing_pkey"), new TableField[] { Routing.ROUTING.ID }, true);
    public static final UniqueKey<RoutingStepRecord> ROUTING_STEP_PKEY = Internal.createUniqueKey(RoutingStep.ROUTING_STEP, DSL.name("routing_step_pkey"), new TableField[] { RoutingStep.ROUTING_STEP.ID }, true);
    public static final UniqueKey<SalesOrderRecord> SALES_ORDER_ORDER_NUMBER_KEY = Internal.createUniqueKey(SalesOrder.SALES_ORDER, DSL.name("sales_order_order_number_key"), new TableField[] { SalesOrder.SALES_ORDER.ORDER_NUMBER }, true);
    public static final UniqueKey<SalesOrderRecord> SALES_ORDER_PKEY = Internal.createUniqueKey(SalesOrder.SALES_ORDER, DSL.name("sales_order_pkey"), new TableField[] { SalesOrder.SALES_ORDER.ID }, true);
    public static final UniqueKey<SalesOrderLineRecord> SALES_ORDER_LINE_PKEY = Internal.createUniqueKey(SalesOrderLine.SALES_ORDER_LINE, DSL.name("sales_order_line_pkey"), new TableField[] { SalesOrderLine.SALES_ORDER_LINE.ID }, true);
    public static final UniqueKey<ShipmentRecord> SHIPMENT_PKEY = Internal.createUniqueKey(Shipment.SHIPMENT, DSL.name("shipment_pkey"), new TableField[] { Shipment.SHIPMENT.ID }, true);
    public static final UniqueKey<ShipmentRecord> SHIPMENT_SHIPMENT_NUMBER_KEY = Internal.createUniqueKey(Shipment.SHIPMENT, DSL.name("shipment_shipment_number_key"), new TableField[] { Shipment.SHIPMENT.SHIPMENT_NUMBER }, true);
    public static final UniqueKey<ShipmentLineRecord> SHIPMENT_LINE_PKEY = Internal.createUniqueKey(ShipmentLine.SHIPMENT_LINE, DSL.name("shipment_line_pkey"), new TableField[] { ShipmentLine.SHIPMENT_LINE.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMPLOYEE_ID_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_employee_id_key"), new TableField[] { Users.USERS.EMPLOYEE_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);
    public static final UniqueKey<WarehouseRecord> WAREHOUSE_CODE_KEY = Internal.createUniqueKey(Warehouse.WAREHOUSE, DSL.name("warehouse_code_key"), new TableField[] { Warehouse.WAREHOUSE.CODE }, true);
    public static final UniqueKey<WarehouseRecord> WAREHOUSE_PKEY = Internal.createUniqueKey(Warehouse.WAREHOUSE, DSL.name("warehouse_pkey"), new TableField[] { Warehouse.WAREHOUSE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BomLineRecord, BomRecord> BOM_LINE__FKDTIRGW5UG01IVDA4WTARFW3QI = Internal.createForeignKey(BomLine.BOM_LINE, DSL.name("fkdtirgw5ug01ivda4wtarfw3qi"), new TableField[] { BomLine.BOM_LINE.BOM_ID }, Keys.BOM_PKEY, new TableField[] { Bom.BOM.ID }, true);
    public static final ForeignKey<GoodsReceiptLineRecord, GoodsReceiptRecord> GOODS_RECEIPT_LINE__FKFF5SCXF5VGRISTHDLEQKHH0P = Internal.createForeignKey(GoodsReceiptLine.GOODS_RECEIPT_LINE, DSL.name("fkff5scxf5vgristhdleqkhh0p"), new TableField[] { GoodsReceiptLine.GOODS_RECEIPT_LINE.GOODS_RECEIPT_ID }, Keys.GOODS_RECEIPT_PKEY, new TableField[] { GoodsReceipt.GOODS_RECEIPT.ID }, true);
    public static final ForeignKey<PurchaseOrderLineRecord, PurchaseOrderRecord> PURCHASE_ORDER_LINE__FK210T80FSGDI4S4G7TLG9VDGKD = Internal.createForeignKey(PurchaseOrderLine.PURCHASE_ORDER_LINE, DSL.name("fk210t80fsgdi4s4g7tlg9vdgkd"), new TableField[] { PurchaseOrderLine.PURCHASE_ORDER_LINE.PURCHASE_ORDER_ID }, Keys.PURCHASE_ORDER_PKEY, new TableField[] { PurchaseOrder.PURCHASE_ORDER.ID }, true);
    public static final ForeignKey<PurchaseRequestLineRecord, PurchaseRequestRecord> PURCHASE_REQUEST_LINE__FKM11FJM2MHKX5C3XJL7H3K3137 = Internal.createForeignKey(PurchaseRequestLine.PURCHASE_REQUEST_LINE, DSL.name("fkm11fjm2mhkx5c3xjl7h3k3137"), new TableField[] { PurchaseRequestLine.PURCHASE_REQUEST_LINE.PURCHASE_REQUEST_ID }, Keys.PURCHASE_REQUEST_PKEY, new TableField[] { PurchaseRequest.PURCHASE_REQUEST.ID }, true);
    public static final ForeignKey<QuoteLineRecord, QuoteRecord> QUOTE_LINE__FKNBXR28WOT0665O7O2FGY4H0XR = Internal.createForeignKey(QuoteLine.QUOTE_LINE, DSL.name("fknbxr28wot0665o7o2fgy4h0xr"), new TableField[] { QuoteLine.QUOTE_LINE.QUOTE_ID }, Keys.QUOTE_PKEY, new TableField[] { Quote.QUOTE.ID }, true);
    public static final ForeignKey<RevenueLineRecord, RevenueRecord> REVENUE_LINE__FKOV8M9QHYFLW6UXIWW8YYSG1WD = Internal.createForeignKey(RevenueLine.REVENUE_LINE, DSL.name("fkov8m9qhyflw6uxiww8yysg1wd"), new TableField[] { RevenueLine.REVENUE_LINE.REVENUE_ID }, Keys.REVENUE_PKEY, new TableField[] { Revenue.REVENUE.ID }, true);
    public static final ForeignKey<RoutingStepRecord, RoutingRecord> ROUTING_STEP__FKS0344EWKFFWRBCEMENEEGEB9U = Internal.createForeignKey(RoutingStep.ROUTING_STEP, DSL.name("fks0344ewkffwrbcemeneegeb9u"), new TableField[] { RoutingStep.ROUTING_STEP.ROUTING_ID }, Keys.ROUTING_PKEY, new TableField[] { Routing.ROUTING.ID }, true);
    public static final ForeignKey<SalesOrderLineRecord, SalesOrderRecord> SALES_ORDER_LINE__FK3HHRMXPWT1CQLNXMTIWPY9WPG = Internal.createForeignKey(SalesOrderLine.SALES_ORDER_LINE, DSL.name("fk3hhrmxpwt1cqlnxmtiwpy9wpg"), new TableField[] { SalesOrderLine.SALES_ORDER_LINE.SALES_ORDER_ID }, Keys.SALES_ORDER_PKEY, new TableField[] { SalesOrder.SALES_ORDER.ID }, true);
    public static final ForeignKey<ShipmentLineRecord, ShipmentRecord> SHIPMENT_LINE__FKCKPH63TMH3WUPC5T2IBCTB5OM = Internal.createForeignKey(ShipmentLine.SHIPMENT_LINE, DSL.name("fkckph63tmh3wupc5t2ibctb5om"), new TableField[] { ShipmentLine.SHIPMENT_LINE.SHIPMENT_ID }, Keys.SHIPMENT_PKEY, new TableField[] { Shipment.SHIPMENT.ID }, true);
}
