/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq;


import com.github.gwiman.mini_mes_backend.jooq.tables.CodeGroup;
import com.github.gwiman.mini_mes_backend.jooq.tables.CommonCode;
import com.github.gwiman.mini_mes_backend.jooq.tables.Employee;
import com.github.gwiman.mini_mes_backend.jooq.tables.EventPublication;
import com.github.gwiman.mini_mes_backend.jooq.tables.Item;
import com.github.gwiman.mini_mes_backend.jooq.tables.Partner;
import com.github.gwiman.mini_mes_backend.jooq.tables.Process;
import com.github.gwiman.mini_mes_backend.jooq.tables.Quote;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrder;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrderLine;
import com.github.gwiman.mini_mes_backend.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.code_group</code>.
     */
    public final CodeGroup CODE_GROUP = CodeGroup.CODE_GROUP;

    /**
     * The table <code>public.common_code</code>.
     */
    public final CommonCode COMMON_CODE = CommonCode.COMMON_CODE;

    /**
     * The table <code>public.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>public.event_publication</code>.
     */
    public final EventPublication EVENT_PUBLICATION = EventPublication.EVENT_PUBLICATION;

    /**
     * The table <code>public.item</code>.
     */
    public final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.partner</code>.
     */
    public final Partner PARTNER = Partner.PARTNER;

    /**
     * The table <code>public.process</code>.
     */
    public final Process PROCESS = Process.PROCESS;

    /**
     * The table <code>public.quote</code>.
     */
    public final Quote QUOTE = Quote.QUOTE;

    /**
     * The table <code>public.quote_line</code>.
     */
    public final QuoteLine QUOTE_LINE = QuoteLine.QUOTE_LINE;

    /**
     * The table <code>public.sales_order</code>.
     */
    public final SalesOrder SALES_ORDER = SalesOrder.SALES_ORDER;

    /**
     * The table <code>public.sales_order_line</code>.
     */
    public final SalesOrderLine SALES_ORDER_LINE = SalesOrderLine.SALES_ORDER_LINE;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeGroup.CODE_GROUP,
            CommonCode.COMMON_CODE,
            Employee.EMPLOYEE,
            EventPublication.EVENT_PUBLICATION,
            Item.ITEM,
            Partner.PARTNER,
            Process.PROCESS,
            Quote.QUOTE,
            QuoteLine.QUOTE_LINE,
            SalesOrder.SALES_ORDER,
            SalesOrderLine.SALES_ORDER_LINE,
            Users.USERS
        );
    }
}
