/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.BomLine;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BomLineRecord extends UpdatableRecordImpl<BomLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bom_line.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bom_line.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.bom_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bom_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.bom_line.bom_id</code>.
     */
    public void setBomId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bom_line.bom_id</code>.
     */
    public Long getBomId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.bom_line.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bom_line.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.bom_line.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bom_line.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.bom_line.material_item_id</code>.
     */
    public void setMaterialItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bom_line.material_item_id</code>.
     */
    public Long getMaterialItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.bom_line.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bom_line.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.bom_line.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.bom_line.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.bom_line.unit</code>.
     */
    public void setUnit(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.bom_line.unit</code>.
     */
    public String getUnit() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.bom_line.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.bom_line.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.bom_line.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.bom_line.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.bom_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.bom_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BomLineRecord
     */
    public BomLineRecord() {
        super(BomLine.BOM_LINE);
    }

    /**
     * Create a detached, initialised BomLineRecord
     */
    public BomLineRecord(BigDecimal quantity, Integer sortOrder, Long bomId, LocalDateTime createdAt, Long id, Long materialItemId, LocalDateTime updatedAt, Long version, String unit, String createdBy, String updatedBy, String remarks) {
        super(BomLine.BOM_LINE);

        setQuantity(quantity);
        setSortOrder(sortOrder);
        setBomId(bomId);
        setCreatedAt(createdAt);
        setId(id);
        setMaterialItemId(materialItemId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setUnit(unit);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
