/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Bom;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BomRecord extends UpdatableRecordImpl<BomRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bom.active_yn</code>.
     */
    public void setActiveYn(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bom.active_yn</code>.
     */
    public Boolean getActiveYn() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>public.bom.valid_from</code>.
     */
    public void setValidFrom(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bom.valid_from</code>.
     */
    public LocalDate getValidFrom() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.bom.valid_to</code>.
     */
    public void setValidTo(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bom.valid_to</code>.
     */
    public LocalDate getValidTo() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.bom.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bom.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.bom.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bom.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.bom.item_id</code>.
     */
    public void setItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bom.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.bom.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bom.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.bom.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.bom.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.bom.version_code</code>.
     */
    public void setVersionCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.bom.version_code</code>.
     */
    public String getVersionCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.bom.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.bom.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.bom.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.bom.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BomRecord
     */
    public BomRecord() {
        super(Bom.BOM);
    }

    /**
     * Create a detached, initialised BomRecord
     */
    public BomRecord(Boolean activeYn, LocalDate validFrom, LocalDate validTo, LocalDateTime createdAt, Long id, Long itemId, LocalDateTime updatedAt, Long version, String versionCode, String createdBy, String updatedBy) {
        super(Bom.BOM);

        setActiveYn(activeYn);
        setValidFrom(validFrom);
        setValidTo(validTo);
        setCreatedAt(createdAt);
        setId(id);
        setItemId(itemId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setVersionCode(versionCode);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
