/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.CodeGroup;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeGroupRecord extends UpdatableRecordImpl<CodeGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.code_group.group_code</code>.
     */
    public void setGroupCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_group.group_code</code>.
     */
    public String getGroupCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.code_group.group_name</code>.
     */
    public void setGroupName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.code_group.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.code_group.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.code_group.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeGroupRecord
     */
    public CodeGroupRecord() {
        super(CodeGroup.CODE_GROUP);
    }

    /**
     * Create a detached, initialised CodeGroupRecord
     */
    public CodeGroupRecord(Long id, String groupCode, String groupName, Integer sortOrder) {
        super(CodeGroup.CODE_GROUP);

        setId(id);
        setGroupCode(groupCode);
        setGroupName(groupName);
        setSortOrder(sortOrder);
        resetChangedOnNotNull();
    }
}
