/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.CommonCode;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonCodeRecord extends UpdatableRecordImpl<CommonCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.common_code.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.common_code.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.common_code.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.common_code.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.common_code.code_group</code>.
     */
    public void setCodeGroup(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.common_code.code_group</code>.
     */
    public String getCodeGroup() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.common_code.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.common_code.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.common_code.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.common_code.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.common_code.use_yn</code>.
     */
    public void setUseYn(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.common_code.use_yn</code>.
     */
    public Boolean getUseYn() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommonCodeRecord
     */
    public CommonCodeRecord() {
        super(CommonCode.COMMON_CODE);
    }

    /**
     * Create a detached, initialised CommonCodeRecord
     */
    public CommonCodeRecord(Long id, String code, String codeGroup, String name, Integer sortOrder, Boolean useYn) {
        super(CommonCode.COMMON_CODE);

        setId(id);
        setCode(code);
        setCodeGroup(codeGroup);
        setName(name);
        setSortOrder(sortOrder);
        setUseYn(useYn);
        resetChangedOnNotNull();
    }
}
