/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.EventPublication;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventPublicationRecord extends UpdatableRecordImpl<EventPublicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.event_publication.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.event_publication.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.event_publication.completion_attempts</code>.
     */
    public void setCompletionAttempts(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.event_publication.completion_attempts</code>.
     */
    public Integer getCompletionAttempts() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.event_publication.completion_date</code>.
     */
    public void setCompletionDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.event_publication.completion_date</code>.
     */
    public OffsetDateTime getCompletionDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.event_publication.event_type</code>.
     */
    public void setEventType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.event_publication.event_type</code>.
     */
    public String getEventType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.event_publication.last_resubmission_date</code>.
     */
    public void setLastResubmissionDate(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.event_publication.last_resubmission_date</code>.
     */
    public OffsetDateTime getLastResubmissionDate() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.event_publication.listener_id</code>.
     */
    public void setListenerId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.event_publication.listener_id</code>.
     */
    public String getListenerId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.event_publication.publication_date</code>.
     */
    public void setPublicationDate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.event_publication.publication_date</code>.
     */
    public OffsetDateTime getPublicationDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.event_publication.serialized_event</code>.
     */
    public void setSerializedEvent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.event_publication.serialized_event</code>.
     */
    public String getSerializedEvent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.event_publication.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.event_publication.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventPublicationRecord
     */
    public EventPublicationRecord() {
        super(EventPublication.EVENT_PUBLICATION);
    }

    /**
     * Create a detached, initialised EventPublicationRecord
     */
    public EventPublicationRecord(UUID id, Integer completionAttempts, OffsetDateTime completionDate, String eventType, OffsetDateTime lastResubmissionDate, String listenerId, OffsetDateTime publicationDate, String serializedEvent, String status) {
        super(EventPublication.EVENT_PUBLICATION);

        setId(id);
        setCompletionAttempts(completionAttempts);
        setCompletionDate(completionDate);
        setEventType(eventType);
        setLastResubmissionDate(lastResubmissionDate);
        setListenerId(listenerId);
        setPublicationDate(publicationDate);
        setSerializedEvent(serializedEvent);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
