/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.GoodsReceiptLine;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsReceiptLineRecord extends UpdatableRecordImpl<GoodsReceiptLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.goods_receipt_line.received_quantity</code>.
     */
    public void setReceivedQuantity(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.received_quantity</code>.
     */
    public BigDecimal getReceivedQuantity() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.goods_receipt_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.goods_receipt_line.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.goods_receipt_line.goods_receipt_id</code>.
     */
    public void setGoodsReceiptId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.goods_receipt_id</code>.
     */
    public Long getGoodsReceiptId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.goods_receipt_line.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.goods_receipt_line.item_id</code>.
     */
    public void setItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.goods_receipt_line.po_line_id</code>.
     */
    public void setPoLineId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.po_line_id</code>.
     */
    public Long getPoLineId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.goods_receipt_line.receipt_type_code</code>.
     */
    public void setReceiptTypeCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.receipt_type_code</code>.
     */
    public String getReceiptTypeCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.goods_receipt_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.goods_receipt_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsReceiptLineRecord
     */
    public GoodsReceiptLineRecord() {
        super(GoodsReceiptLine.GOODS_RECEIPT_LINE);
    }

    /**
     * Create a detached, initialised GoodsReceiptLineRecord
     */
    public GoodsReceiptLineRecord(BigDecimal receivedQuantity, Integer sortOrder, BigDecimal unitPrice, Long goodsReceiptId, Long id, Long itemId, Long poLineId, String receiptTypeCode, String remarks) {
        super(GoodsReceiptLine.GOODS_RECEIPT_LINE);

        setReceivedQuantity(receivedQuantity);
        setSortOrder(sortOrder);
        setUnitPrice(unitPrice);
        setGoodsReceiptId(goodsReceiptId);
        setId(id);
        setItemId(itemId);
        setPoLineId(poLineId);
        setReceiptTypeCode(receiptTypeCode);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
