/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.InventoryTx;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryTxRecord extends UpdatableRecordImpl<InventoryTxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.inventory_tx.qty_delta</code>.
     */
    public void setQtyDelta(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.inventory_tx.qty_delta</code>.
     */
    public BigDecimal getQtyDelta() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.inventory_tx.tx_date</code>.
     */
    public void setTxDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.inventory_tx.tx_date</code>.
     */
    public LocalDate getTxDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.inventory_tx.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.inventory_tx.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.inventory_tx.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.inventory_tx.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.inventory_tx.item_id</code>.
     */
    public void setItemId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.inventory_tx.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.inventory_tx.ref_id</code>.
     */
    public void setRefId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.inventory_tx.ref_id</code>.
     */
    public Long getRefId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.inventory_tx.transfer_id</code>.
     */
    public void setTransferId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.inventory_tx.transfer_id</code>.
     */
    public Long getTransferId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.inventory_tx.warehouse_id</code>.
     */
    public void setWarehouseId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.inventory_tx.warehouse_id</code>.
     */
    public Long getWarehouseId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.inventory_tx.ref_type</code>.
     */
    public void setRefType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.inventory_tx.ref_type</code>.
     */
    public String getRefType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.inventory_tx.tx_type</code>.
     */
    public void setTxType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.inventory_tx.tx_type</code>.
     */
    public String getTxType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.inventory_tx.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.inventory_tx.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.inventory_tx.lot_no</code>.
     */
    public void setLotNo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.inventory_tx.lot_no</code>.
     */
    public String getLotNo() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryTxRecord
     */
    public InventoryTxRecord() {
        super(InventoryTx.INVENTORY_TX);
    }

    /**
     * Create a detached, initialised InventoryTxRecord
     */
    public InventoryTxRecord(BigDecimal qtyDelta, LocalDate txDate, LocalDateTime createdAt, Long id, Long itemId, Long refId, Long transferId, Long warehouseId, String refType, String txType, String createdBy, String lotNo) {
        super(InventoryTx.INVENTORY_TX);

        setQtyDelta(qtyDelta);
        setTxDate(txDate);
        setCreatedAt(createdAt);
        setId(id);
        setItemId(itemId);
        setRefId(refId);
        setTransferId(transferId);
        setWarehouseId(warehouseId);
        setRefType(refType);
        setTxType(txType);
        setCreatedBy(createdBy);
        setLotNo(lotNo);
        resetChangedOnNotNull();
    }
}
