/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.InventoryLot;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryLotRecord extends UpdatableRecordImpl<InventoryLotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.inventory_lot.expiry_date</code>.
     */
    public void setExpiryDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.inventory_lot.expiry_date</code>.
     */
    public LocalDate getExpiryDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>public.inventory_lot.qty_on_hand</code>.
     */
    public void setQtyOnHand(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.inventory_lot.qty_on_hand</code>.
     */
    public BigDecimal getQtyOnHand() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.inventory_lot.qty_reserved</code>.
     */
    public void setQtyReserved(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.inventory_lot.qty_reserved</code>.
     */
    public BigDecimal getQtyReserved() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.inventory_lot.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.inventory_lot.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.inventory_lot.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.inventory_lot.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.inventory_lot.item_id</code>.
     */
    public void setItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.inventory_lot.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.inventory_lot.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.inventory_lot.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.inventory_lot.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.inventory_lot.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.inventory_lot.warehouse_id</code>.
     */
    public void setWarehouseId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.inventory_lot.warehouse_id</code>.
     */
    public Long getWarehouseId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.inventory_lot.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.inventory_lot.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.inventory_lot.lot_no</code>.
     */
    public void setLotNo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.inventory_lot.lot_no</code>.
     */
    public String getLotNo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.inventory_lot.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.inventory_lot.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryLotRecord
     */
    public InventoryLotRecord() {
        super(InventoryLot.INVENTORY_LOT);
    }

    /**
     * Create a detached, initialised InventoryLotRecord
     */
    public InventoryLotRecord(LocalDate expiryDate, BigDecimal qtyOnHand, BigDecimal qtyReserved, LocalDateTime createdAt, Long id, Long itemId, LocalDateTime updatedAt, Long version, Long warehouseId, String createdBy, String lotNo, String updatedBy) {
        super(InventoryLot.INVENTORY_LOT);

        setExpiryDate(expiryDate);
        setQtyOnHand(qtyOnHand);
        setQtyReserved(qtyReserved);
        setCreatedAt(createdAt);
        setId(id);
        setItemId(itemId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setWarehouseId(warehouseId);
        setCreatedBy(createdBy);
        setLotNo(lotNo);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
