/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Inventory;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.inventory.qty_on_hand</code>.
     */
    public void setQtyOnHand(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.inventory.qty_on_hand</code>.
     */
    public BigDecimal getQtyOnHand() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.inventory.qty_reserved</code>.
     */
    public void setQtyReserved(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.inventory.qty_reserved</code>.
     */
    public BigDecimal getQtyReserved() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.inventory.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.inventory.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.inventory.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.inventory.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.inventory.item_id</code>.
     */
    public void setItemId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.inventory.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.inventory.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.inventory.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.inventory.version</code>.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.inventory.version</code>.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.inventory.warehouse_id</code>.
     */
    public void setWarehouseId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.inventory.warehouse_id</code>.
     */
    public Long getWarehouseId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.inventory.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.inventory.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.inventory.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.inventory.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(BigDecimal qtyOnHand, BigDecimal qtyReserved, LocalDateTime createdAt, Long id, Long itemId, LocalDateTime updatedAt, Long version, Long warehouseId, String createdBy, String updatedBy) {
        super(Inventory.INVENTORY);

        setQtyOnHand(qtyOnHand);
        setQtyReserved(qtyReserved);
        setCreatedAt(createdAt);
        setId(id);
        setItemId(itemId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setWarehouseId(warehouseId);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
