/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.ItemPrice;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemPriceRecord extends UpdatableRecordImpl<ItemPriceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item_price.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item_price.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.item_price.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item_price.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.item_price.id</code>.
     */
    public void setId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item_price.id</code>.
     */
    public Long getId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.item_price.item_id</code>.
     */
    public void setItemId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item_price.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.item_price.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item_price.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.item_price.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item_price.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.item_price.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item_price.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item_price.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item_price.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.item_price.remarks</code>.
     */
    public void setRemarks(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.item_price.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemPriceRecord
     */
    public ItemPriceRecord() {
        super(ItemPrice.ITEM_PRICE);
    }

    /**
     * Create a detached, initialised ItemPriceRecord
     */
    public ItemPriceRecord(BigDecimal unitPrice, LocalDateTime createdAt, Long id, Long itemId, LocalDateTime updatedAt, Long version, String createdBy, String updatedBy, String remarks) {
        super(ItemPrice.ITEM_PRICE);

        setUnitPrice(unitPrice);
        setCreatedAt(createdAt);
        setId(id);
        setItemId(itemId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
