/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Item;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.item.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.item_type_code</code>.
     */
    public void setItemTypeCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item.item_type_code</code>.
     */
    public String getItemTypeCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.item.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.item.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.item.spec</code>.
     */
    public void setSpec(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item.spec</code>.
     */
    public String getSpec() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item.unit</code>.
     */
    public void setUnit(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item.unit</code>.
     */
    public String getUnit() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.item.use_yn</code>.
     */
    public void setUseYn(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.item.use_yn</code>.
     */
    public Boolean getUseYn() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Long id, String code, String description, String itemTypeCode, String name, Integer sortOrder, String spec, String unit, Boolean useYn) {
        super(Item.ITEM);

        setId(id);
        setCode(code);
        setDescription(description);
        setItemTypeCode(itemTypeCode);
        setName(name);
        setSortOrder(sortOrder);
        setSpec(spec);
        setUnit(unit);
        setUseYn(useYn);
        resetChangedOnNotNull();
    }
}
