/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Partner;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartnerRecord extends UpdatableRecordImpl<PartnerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.partner.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.partner.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.partner.address</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.partner.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.partner.business_number</code>.
     */
    public void setBusinessNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.partner.business_number</code>.
     */
    public String getBusinessNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.partner.ceo_name</code>.
     */
    public void setCeoName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.partner.ceo_name</code>.
     */
    public String getCeoName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.partner.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.partner.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.partner.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.partner.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.partner.phone1</code>.
     */
    public void setPhone1(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.partner.phone1</code>.
     */
    public String getPhone1() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.partner.phone2</code>.
     */
    public void setPhone2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.partner.phone2</code>.
     */
    public String getPhone2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.partner.trade_type_code</code>.
     */
    public void setTradeTypeCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.partner.trade_type_code</code>.
     */
    public String getTradeTypeCode() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartnerRecord
     */
    public PartnerRecord() {
        super(Partner.PARTNER);
    }

    /**
     * Create a detached, initialised PartnerRecord
     */
    public PartnerRecord(Long id, String address, String businessNumber, String ceoName, String code, String name, String phone1, String phone2, String tradeTypeCode) {
        super(Partner.PARTNER);

        setId(id);
        setAddress(address);
        setBusinessNumber(businessNumber);
        setCeoName(ceoName);
        setCode(code);
        setName(name);
        setPhone1(phone1);
        setPhone2(phone2);
        setTradeTypeCode(tradeTypeCode);
        resetChangedOnNotNull();
    }
}
