/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Process;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessRecord extends UpdatableRecordImpl<ProcessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.process.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.process.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.process.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.process.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.process.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.process.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.process.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.process.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.process.process_type_code</code>.
     */
    public void setProcessTypeCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.process.process_type_code</code>.
     */
    public String getProcessTypeCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.process.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.process.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.process.standard_time</code>.
     */
    public void setStandardTime(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.process.standard_time</code>.
     */
    public Integer getStandardTime() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessRecord
     */
    public ProcessRecord() {
        super(Process.PROCESS);
    }

    /**
     * Create a detached, initialised ProcessRecord
     */
    public ProcessRecord(Long id, String code, String description, String name, String processTypeCode, Integer sortOrder, Integer standardTime) {
        super(Process.PROCESS);

        setId(id);
        setCode(code);
        setDescription(description);
        setName(name);
        setProcessTypeCode(processTypeCode);
        setSortOrder(sortOrder);
        setStandardTime(standardTime);
        resetChangedOnNotNull();
    }
}
