/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseOrderLine;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrderLineRecord extends UpdatableRecordImpl<PurchaseOrderLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_order_line.ordered_quantity</code>.
     */
    public void setOrderedQuantity(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.ordered_quantity</code>.
     */
    public BigDecimal getOrderedQuantity() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.purchase_order_line.required_date</code>.
     */
    public void setRequiredDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.required_date</code>.
     */
    public LocalDate getRequiredDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.purchase_order_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.purchase_order_line.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.purchase_order_line.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.purchase_order_line.item_id</code>.
     */
    public void setItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.purchase_order_line.pr_line_id</code>.
     */
    public void setPrLineId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.pr_line_id</code>.
     */
    public Long getPrLineId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.purchase_order_line.purchase_order_id</code>.
     */
    public void setPurchaseOrderId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.purchase_order_id</code>.
     */
    public Long getPurchaseOrderId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.purchase_order_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.purchase_order_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseOrderLineRecord
     */
    public PurchaseOrderLineRecord() {
        super(PurchaseOrderLine.PURCHASE_ORDER_LINE);
    }

    /**
     * Create a detached, initialised PurchaseOrderLineRecord
     */
    public PurchaseOrderLineRecord(BigDecimal orderedQuantity, LocalDate requiredDate, Integer sortOrder, BigDecimal unitPrice, Long id, Long itemId, Long prLineId, Long purchaseOrderId, String remarks) {
        super(PurchaseOrderLine.PURCHASE_ORDER_LINE);

        setOrderedQuantity(orderedQuantity);
        setRequiredDate(requiredDate);
        setSortOrder(sortOrder);
        setUnitPrice(unitPrice);
        setId(id);
        setItemId(itemId);
        setPrLineId(prLineId);
        setPurchaseOrderId(purchaseOrderId);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
