/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseRequest;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRequestRecord extends UpdatableRecordImpl<PurchaseRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_request.request_date</code>.
     */
    public void setRequestDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_request.request_date</code>.
     */
    public LocalDate getRequestDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>public.purchase_request.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_request.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.purchase_request.id</code>.
     */
    public void setId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_request.id</code>.
     */
    public Long getId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.purchase_request.requester_id</code>.
     */
    public void setRequesterId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase_request.requester_id</code>.
     */
    public Long getRequesterId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.purchase_request.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.purchase_request.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.purchase_request.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.purchase_request.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.purchase_request.status_code</code>.
     */
    public void setStatusCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.purchase_request.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.purchase_request.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.purchase_request.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.purchase_request.request_number</code>.
     */
    public void setRequestNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.purchase_request.request_number</code>.
     */
    public String getRequestNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.purchase_request.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.purchase_request.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.purchase_request.remarks</code>.
     */
    public void setRemarks(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.purchase_request.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseRequestRecord
     */
    public PurchaseRequestRecord() {
        super(PurchaseRequest.PURCHASE_REQUEST);
    }

    /**
     * Create a detached, initialised PurchaseRequestRecord
     */
    public PurchaseRequestRecord(LocalDate requestDate, LocalDateTime createdAt, Long id, Long requesterId, LocalDateTime updatedAt, Long version, String statusCode, String createdBy, String requestNumber, String updatedBy, String remarks) {
        super(PurchaseRequest.PURCHASE_REQUEST);

        setRequestDate(requestDate);
        setCreatedAt(createdAt);
        setId(id);
        setRequesterId(requesterId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setStatusCode(statusCode);
        setCreatedBy(createdBy);
        setRequestNumber(requestNumber);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
