/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseRequestLine;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRequestLineRecord extends UpdatableRecordImpl<PurchaseRequestLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_request_line.requested_quantity</code>.
     */
    public void setRequestedQuantity(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.requested_quantity</code>.
     */
    public BigDecimal getRequestedQuantity() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.purchase_request_line.required_date</code>.
     */
    public void setRequiredDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.required_date</code>.
     */
    public LocalDate getRequiredDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.purchase_request_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.purchase_request_line.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.purchase_request_line.item_id</code>.
     */
    public void setItemId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.purchase_request_line.purchase_request_id</code>.
     */
    public void setPurchaseRequestId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.purchase_request_id</code>.
     */
    public Long getPurchaseRequestId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.purchase_request_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.purchase_request_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseRequestLineRecord
     */
    public PurchaseRequestLineRecord() {
        super(PurchaseRequestLine.PURCHASE_REQUEST_LINE);
    }

    /**
     * Create a detached, initialised PurchaseRequestLineRecord
     */
    public PurchaseRequestLineRecord(BigDecimal requestedQuantity, LocalDate requiredDate, Integer sortOrder, Long id, Long itemId, Long purchaseRequestId, String remarks) {
        super(PurchaseRequestLine.PURCHASE_REQUEST_LINE);

        setRequestedQuantity(requestedQuantity);
        setRequiredDate(requiredDate);
        setSortOrder(sortOrder);
        setId(id);
        setItemId(itemId);
        setPurchaseRequestId(purchaseRequestId);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
