/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Quote;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuoteRecord extends UpdatableRecordImpl<QuoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quote.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.quote.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.quote.quote_date</code>.
     */
    public void setQuoteDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.quote.quote_date</code>.
     */
    public LocalDate getQuoteDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.quote.quote_number</code>.
     */
    public void setQuoteNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.quote.quote_number</code>.
     */
    public String getQuoteNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quote.remarks</code>.
     */
    public void setRemarks(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.quote.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.quote.status_code</code>.
     */
    public void setStatusCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.quote.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.quote.valid_until</code>.
     */
    public void setValidUntil(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.quote.valid_until</code>.
     */
    public LocalDate getValidUntil() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.quote.employee_id</code>.
     */
    public void setEmployeeId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.quote.employee_id</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.quote.partner_id</code>.
     */
    public void setPartnerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.quote.partner_id</code>.
     */
    public Long getPartnerId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuoteRecord
     */
    public QuoteRecord() {
        super(Quote.QUOTE);
    }

    /**
     * Create a detached, initialised QuoteRecord
     */
    public QuoteRecord(Long id, LocalDate quoteDate, String quoteNumber, String remarks, String statusCode, LocalDate validUntil, Long employeeId, Long partnerId) {
        super(Quote.QUOTE);

        setId(id);
        setQuoteDate(quoteDate);
        setQuoteNumber(quoteNumber);
        setRemarks(remarks);
        setStatusCode(statusCode);
        setValidUntil(validUntil);
        setEmployeeId(employeeId);
        setPartnerId(partnerId);
        resetChangedOnNotNull();
    }
}
