/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Revenue;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevenueRecord extends UpdatableRecordImpl<RevenueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.revenue.revenue_date</code>.
     */
    public void setRevenueDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.revenue.revenue_date</code>.
     */
    public LocalDate getRevenueDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>public.revenue.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.revenue.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.revenue.employee_id</code>.
     */
    public void setEmployeeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.revenue.employee_id</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.revenue.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.revenue.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.revenue.partner_id</code>.
     */
    public void setPartnerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.revenue.partner_id</code>.
     */
    public Long getPartnerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.revenue.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.revenue.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.revenue.version</code>.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.revenue.version</code>.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.revenue.status_code</code>.
     */
    public void setStatusCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.revenue.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.revenue.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.revenue.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.revenue.revenue_number</code>.
     */
    public void setRevenueNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.revenue.revenue_number</code>.
     */
    public String getRevenueNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.revenue.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.revenue.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.revenue.remarks</code>.
     */
    public void setRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.revenue.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevenueRecord
     */
    public RevenueRecord() {
        super(Revenue.REVENUE);
    }

    /**
     * Create a detached, initialised RevenueRecord
     */
    public RevenueRecord(LocalDate revenueDate, LocalDateTime createdAt, Long employeeId, Long id, Long partnerId, LocalDateTime updatedAt, Long version, String statusCode, String createdBy, String revenueNumber, String updatedBy, String remarks) {
        super(Revenue.REVENUE);

        setRevenueDate(revenueDate);
        setCreatedAt(createdAt);
        setEmployeeId(employeeId);
        setId(id);
        setPartnerId(partnerId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setStatusCode(statusCode);
        setCreatedBy(createdBy);
        setRevenueNumber(revenueNumber);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
