/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.RevenueLine;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevenueLineRecord extends UpdatableRecordImpl<RevenueLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.revenue_line.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.revenue_line.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.revenue_line.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.revenue_line.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.revenue_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.revenue_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.revenue_line.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.revenue_line.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.revenue_line.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.revenue_line.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.revenue_line.item_id</code>.
     */
    public void setItemId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.revenue_line.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.revenue_line.revenue_id</code>.
     */
    public void setRevenueId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.revenue_line.revenue_id</code>.
     */
    public Long getRevenueId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.revenue_line.sales_order_id</code>.
     */
    public void setSalesOrderId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.revenue_line.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.revenue_line.sales_order_line_id</code>.
     */
    public void setSalesOrderLineId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.revenue_line.sales_order_line_id</code>.
     */
    public Long getSalesOrderLineId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.revenue_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.revenue_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevenueLineRecord
     */
    public RevenueLineRecord() {
        super(RevenueLine.REVENUE_LINE);
    }

    /**
     * Create a detached, initialised RevenueLineRecord
     */
    public RevenueLineRecord(BigDecimal amount, BigDecimal quantity, Integer sortOrder, BigDecimal unitPrice, Long id, Long itemId, Long revenueId, Long salesOrderId, Long salesOrderLineId, String remarks) {
        super(RevenueLine.REVENUE_LINE);

        setAmount(amount);
        setQuantity(quantity);
        setSortOrder(sortOrder);
        setUnitPrice(unitPrice);
        setId(id);
        setItemId(itemId);
        setRevenueId(revenueId);
        setSalesOrderId(salesOrderId);
        setSalesOrderLineId(salesOrderLineId);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
