/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.RoutingStep;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutingStepRecord extends UpdatableRecordImpl<RoutingStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.routing_step.standard_time</code>.
     */
    public void setStandardTime(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.routing_step.standard_time</code>.
     */
    public Integer getStandardTime() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.routing_step.step_order</code>.
     */
    public void setStepOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.routing_step.step_order</code>.
     */
    public Integer getStepOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.routing_step.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.routing_step.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.routing_step.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.routing_step.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.routing_step.process_id</code>.
     */
    public void setProcessId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.routing_step.process_id</code>.
     */
    public Long getProcessId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.routing_step.routing_id</code>.
     */
    public void setRoutingId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.routing_step.routing_id</code>.
     */
    public Long getRoutingId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.routing_step.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.routing_step.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.routing_step.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.routing_step.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.routing_step.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.routing_step.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.routing_step.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.routing_step.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.routing_step.remarks</code>.
     */
    public void setRemarks(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.routing_step.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutingStepRecord
     */
    public RoutingStepRecord() {
        super(RoutingStep.ROUTING_STEP);
    }

    /**
     * Create a detached, initialised RoutingStepRecord
     */
    public RoutingStepRecord(Integer standardTime, Integer stepOrder, LocalDateTime createdAt, Long id, Long processId, Long routingId, LocalDateTime updatedAt, Long version, String createdBy, String updatedBy, String remarks) {
        super(RoutingStep.ROUTING_STEP);

        setStandardTime(standardTime);
        setStepOrder(stepOrder);
        setCreatedAt(createdAt);
        setId(id);
        setProcessId(processId);
        setRoutingId(routingId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
