/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Routing;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutingRecord extends UpdatableRecordImpl<RoutingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.routing.active_yn</code>.
     */
    public void setActiveYn(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.routing.active_yn</code>.
     */
    public Boolean getActiveYn() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>public.routing.bom_id</code>.
     */
    public void setBomId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.routing.bom_id</code>.
     */
    public Long getBomId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.routing.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.routing.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.routing.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.routing.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.routing.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.routing.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.routing.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.routing.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.routing.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.routing.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.routing.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.routing.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutingRecord
     */
    public RoutingRecord() {
        super(Routing.ROUTING);
    }

    /**
     * Create a detached, initialised RoutingRecord
     */
    public RoutingRecord(Boolean activeYn, Long bomId, LocalDateTime createdAt, Long id, LocalDateTime updatedAt, Long version, String createdBy, String updatedBy) {
        super(Routing.ROUTING);

        setActiveYn(activeYn);
        setBomId(bomId);
        setCreatedAt(createdAt);
        setId(id);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
