/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrder;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderRecord extends UpdatableRecordImpl<SalesOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sales_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sales_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sales_order.delivery_date</code>.
     */
    public void setDeliveryDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sales_order.delivery_date</code>.
     */
    public LocalDate getDeliveryDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.sales_order.order_date</code>.
     */
    public void setOrderDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sales_order.order_date</code>.
     */
    public LocalDate getOrderDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.sales_order.order_number</code>.
     */
    public void setOrderNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sales_order.order_number</code>.
     */
    public String getOrderNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sales_order.remarks</code>.
     */
    public void setRemarks(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sales_order.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sales_order.status_code</code>.
     */
    public void setStatusCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sales_order.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.sales_order.employee_id</code>.
     */
    public void setEmployeeId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sales_order.employee_id</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.sales_order.partner_id</code>.
     */
    public void setPartnerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.sales_order.partner_id</code>.
     */
    public Long getPartnerId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.sales_order.quote_id</code>.
     */
    public void setQuoteId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.sales_order.quote_id</code>.
     */
    public Long getQuoteId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesOrderRecord
     */
    public SalesOrderRecord() {
        super(SalesOrder.SALES_ORDER);
    }

    /**
     * Create a detached, initialised SalesOrderRecord
     */
    public SalesOrderRecord(Long id, LocalDate deliveryDate, LocalDate orderDate, String orderNumber, String remarks, String statusCode, Long employeeId, Long partnerId, Long quoteId) {
        super(SalesOrder.SALES_ORDER);

        setId(id);
        setDeliveryDate(deliveryDate);
        setOrderDate(orderDate);
        setOrderNumber(orderNumber);
        setRemarks(remarks);
        setStatusCode(statusCode);
        setEmployeeId(employeeId);
        setPartnerId(partnerId);
        setQuoteId(quoteId);
        resetChangedOnNotNull();
    }
}
