/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Shipment;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShipmentRecord extends UpdatableRecordImpl<ShipmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shipment.shipment_date</code>.
     */
    public void setShipmentDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shipment.shipment_date</code>.
     */
    public LocalDate getShipmentDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>public.shipment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shipment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.shipment.employee_id</code>.
     */
    public void setEmployeeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shipment.employee_id</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.shipment.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shipment.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.shipment.partner_id</code>.
     */
    public void setPartnerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shipment.partner_id</code>.
     */
    public Long getPartnerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.shipment.sales_order_id</code>.
     */
    public void setSalesOrderId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shipment.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.shipment.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shipment.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.shipment.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shipment.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.shipment.status_code</code>.
     */
    public void setStatusCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.shipment.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.shipment.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.shipment.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.shipment.shipment_number</code>.
     */
    public void setShipmentNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.shipment.shipment_number</code>.
     */
    public String getShipmentNumber() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.shipment.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.shipment.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.shipment.remarks</code>.
     */
    public void setRemarks(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.shipment.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShipmentRecord
     */
    public ShipmentRecord() {
        super(Shipment.SHIPMENT);
    }

    /**
     * Create a detached, initialised ShipmentRecord
     */
    public ShipmentRecord(LocalDate shipmentDate, LocalDateTime createdAt, Long employeeId, Long id, Long partnerId, Long salesOrderId, LocalDateTime updatedAt, Long version, String statusCode, String createdBy, String shipmentNumber, String updatedBy, String remarks) {
        super(Shipment.SHIPMENT);

        setShipmentDate(shipmentDate);
        setCreatedAt(createdAt);
        setEmployeeId(employeeId);
        setId(id);
        setPartnerId(partnerId);
        setSalesOrderId(salesOrderId);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setStatusCode(statusCode);
        setCreatedBy(createdBy);
        setShipmentNumber(shipmentNumber);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
