/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.ShipmentLine;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShipmentLineRecord extends UpdatableRecordImpl<ShipmentLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shipment_line.actual_amount</code>.
     */
    public void setActualAmount(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shipment_line.actual_amount</code>.
     */
    public BigDecimal getActualAmount() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.shipment_line.actual_quantity</code>.
     */
    public void setActualQuantity(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shipment_line.actual_quantity</code>.
     */
    public BigDecimal getActualQuantity() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.shipment_line.planned_amount</code>.
     */
    public void setPlannedAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shipment_line.planned_amount</code>.
     */
    public BigDecimal getPlannedAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.shipment_line.planned_quantity</code>.
     */
    public void setPlannedQuantity(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shipment_line.planned_quantity</code>.
     */
    public BigDecimal getPlannedQuantity() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.shipment_line.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shipment_line.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.shipment_line.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shipment_line.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.shipment_line.id</code>.
     */
    public void setId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shipment_line.id</code>.
     */
    public Long getId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.shipment_line.item_id</code>.
     */
    public void setItemId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shipment_line.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.shipment_line.sales_order_line_id</code>.
     */
    public void setSalesOrderLineId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.shipment_line.sales_order_line_id</code>.
     */
    public Long getSalesOrderLineId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.shipment_line.shipment_id</code>.
     */
    public void setShipmentId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.shipment_line.shipment_id</code>.
     */
    public Long getShipmentId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.shipment_line.remarks</code>.
     */
    public void setRemarks(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.shipment_line.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShipmentLineRecord
     */
    public ShipmentLineRecord() {
        super(ShipmentLine.SHIPMENT_LINE);
    }

    /**
     * Create a detached, initialised ShipmentLineRecord
     */
    public ShipmentLineRecord(BigDecimal actualAmount, BigDecimal actualQuantity, BigDecimal plannedAmount, BigDecimal plannedQuantity, Integer sortOrder, BigDecimal unitPrice, Long id, Long itemId, Long salesOrderLineId, Long shipmentId, String remarks) {
        super(ShipmentLine.SHIPMENT_LINE);

        setActualAmount(actualAmount);
        setActualQuantity(actualQuantity);
        setPlannedAmount(plannedAmount);
        setPlannedQuantity(plannedQuantity);
        setSortOrder(sortOrder);
        setUnitPrice(unitPrice);
        setId(id);
        setItemId(itemId);
        setSalesOrderLineId(salesOrderLineId);
        setShipmentId(shipmentId);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
