/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables.records;


import com.github.gwiman.mini_mes_backend.jooq.tables.Warehouse;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseRecord extends UpdatableRecordImpl<WarehouseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.warehouse.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.warehouse.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.warehouse.use_yn</code>.
     */
    public void setUseYn(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.warehouse.use_yn</code>.
     */
    public Boolean getUseYn() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.warehouse.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.warehouse.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.warehouse.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.warehouse.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.warehouse.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.warehouse.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.warehouse.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.warehouse.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.warehouse.warehouse_type_code</code>.
     */
    public void setWarehouseTypeCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.warehouse.warehouse_type_code</code>.
     */
    public String getWarehouseTypeCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.warehouse.code</code>.
     */
    public void setCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.warehouse.code</code>.
     */
    public String getCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.warehouse.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.warehouse.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.warehouse.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.warehouse.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.warehouse.name</code>.
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.warehouse.name</code>.
     */
    public String getName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.warehouse.description</code>.
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.warehouse.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WarehouseRecord
     */
    public WarehouseRecord() {
        super(Warehouse.WAREHOUSE);
    }

    /**
     * Create a detached, initialised WarehouseRecord
     */
    public WarehouseRecord(Integer sortOrder, Boolean useYn, LocalDateTime createdAt, Long id, LocalDateTime updatedAt, Long version, String warehouseTypeCode, String code, String createdBy, String updatedBy, String name, String description) {
        super(Warehouse.WAREHOUSE);

        setSortOrder(sortOrder);
        setUseYn(useYn);
        setCreatedAt(createdAt);
        setId(id);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setWarehouseTypeCode(warehouseTypeCode);
        setCode(code);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
