/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Bom.BomPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.BomLineRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BomLine extends TableImpl<BomLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bom_line</code>
     */
    public static final BomLine BOM_LINE = new BomLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BomLineRecord> getRecordType() {
        return BomLineRecord.class;
    }

    /**
     * The column <code>public.bom_line.quantity</code>.
     */
    public final TableField<BomLineRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.bom_line.sort_order</code>.
     */
    public final TableField<BomLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.bom_line.bom_id</code>.
     */
    public final TableField<BomLineRecord, Long> BOM_ID = createField(DSL.name("bom_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.bom_line.created_at</code>.
     */
    public final TableField<BomLineRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.bom_line.id</code>.
     */
    public final TableField<BomLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.bom_line.material_item_id</code>.
     */
    public final TableField<BomLineRecord, Long> MATERIAL_ITEM_ID = createField(DSL.name("material_item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.bom_line.updated_at</code>.
     */
    public final TableField<BomLineRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.bom_line.version</code>.
     */
    public final TableField<BomLineRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.bom_line.unit</code>.
     */
    public final TableField<BomLineRecord, String> UNIT = createField(DSL.name("unit"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.bom_line.created_by</code>.
     */
    public final TableField<BomLineRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.bom_line.updated_by</code>.
     */
    public final TableField<BomLineRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.bom_line.remarks</code>.
     */
    public final TableField<BomLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private BomLine(Name alias, Table<BomLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BomLine(Name alias, Table<BomLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bom_line</code> table reference
     */
    public BomLine(String alias) {
        this(DSL.name(alias), BOM_LINE);
    }

    /**
     * Create an aliased <code>public.bom_line</code> table reference
     */
    public BomLine(Name alias) {
        this(alias, BOM_LINE);
    }

    /**
     * Create a <code>public.bom_line</code> table reference
     */
    public BomLine() {
        this(DSL.name("bom_line"), null);
    }

    public <O extends Record> BomLine(Table<O> path, ForeignKey<O, BomLineRecord> childPath, InverseForeignKey<O, BomLineRecord> parentPath) {
        super(path, childPath, parentPath, BOM_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BomLinePath extends BomLine implements Path<BomLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BomLinePath(Table<O> path, ForeignKey<O, BomLineRecord> childPath, InverseForeignKey<O, BomLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BomLinePath(Name alias, Table<BomLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BomLinePath as(String alias) {
            return new BomLinePath(DSL.name(alias), this);
        }

        @Override
        public BomLinePath as(Name alias) {
            return new BomLinePath(alias, this);
        }

        @Override
        public BomLinePath as(Table<?> alias) {
            return new BomLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<BomLineRecord, Long> getIdentity() {
        return (Identity<BomLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BomLineRecord> getPrimaryKey() {
        return Keys.BOM_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<BomLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOM_LINE__FKDTIRGW5UG01IVDA4WTARFW3QI);
    }

    private transient BomPath _bom;

    /**
     * Get the implicit join path to the <code>public.bom</code> table.
     */
    public BomPath bom() {
        if (_bom == null)
            _bom = new BomPath(this, Keys.BOM_LINE__FKDTIRGW5UG01IVDA4WTARFW3QI, null);

        return _bom;
    }

    @Override
    public BomLine as(String alias) {
        return new BomLine(DSL.name(alias), this);
    }

    @Override
    public BomLine as(Name alias) {
        return new BomLine(alias, this);
    }

    @Override
    public BomLine as(Table<?> alias) {
        return new BomLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BomLine rename(String name) {
        return new BomLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BomLine rename(Name name) {
        return new BomLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BomLine rename(Table<?> name) {
        return new BomLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine where(Condition condition) {
        return new BomLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BomLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BomLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BomLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BomLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BomLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
