/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.CodeGroupRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeGroup extends TableImpl<CodeGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_group</code>
     */
    public static final CodeGroup CODE_GROUP = new CodeGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeGroupRecord> getRecordType() {
        return CodeGroupRecord.class;
    }

    /**
     * The column <code>public.code_group.id</code>.
     */
    public final TableField<CodeGroupRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.code_group.group_code</code>.
     */
    public final TableField<CodeGroupRecord, String> GROUP_CODE = createField(DSL.name("group_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.code_group.group_name</code>.
     */
    public final TableField<CodeGroupRecord, String> GROUP_NAME = createField(DSL.name("group_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.code_group.sort_order</code>.
     */
    public final TableField<CodeGroupRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    private CodeGroup(Name alias, Table<CodeGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeGroup(Name alias, Table<CodeGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_group</code> table reference
     */
    public CodeGroup(String alias) {
        this(DSL.name(alias), CODE_GROUP);
    }

    /**
     * Create an aliased <code>public.code_group</code> table reference
     */
    public CodeGroup(Name alias) {
        this(alias, CODE_GROUP);
    }

    /**
     * Create a <code>public.code_group</code> table reference
     */
    public CodeGroup() {
        this(DSL.name("code_group"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CodeGroupRecord, Long> getIdentity() {
        return (Identity<CodeGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CodeGroupRecord> getPrimaryKey() {
        return Keys.CODE_GROUP_PKEY;
    }

    @Override
    public List<UniqueKey<CodeGroupRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UKANYWI85GA0C2V0JC8Q8UEKWM5);
    }

    @Override
    public CodeGroup as(String alias) {
        return new CodeGroup(DSL.name(alias), this);
    }

    @Override
    public CodeGroup as(Name alias) {
        return new CodeGroup(alias, this);
    }

    @Override
    public CodeGroup as(Table<?> alias) {
        return new CodeGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeGroup rename(String name) {
        return new CodeGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeGroup rename(Name name) {
        return new CodeGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeGroup rename(Table<?> name) {
        return new CodeGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup where(Condition condition) {
        return new CodeGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
