/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Quote.QuotePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.EmployeeRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends TableImpl<EmployeeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.employee</code>
     */
    public static final Employee EMPLOYEE = new Employee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeRecord> getRecordType() {
        return EmployeeRecord.class;
    }

    /**
     * The column <code>public.employee.id</code>.
     */
    public final TableField<EmployeeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.employee.code</code>.
     */
    public final TableField<EmployeeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.employee.dept_code</code>.
     */
    public final TableField<EmployeeRecord, String> DEPT_CODE = createField(DSL.name("dept_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.employee.email</code>.
     */
    public final TableField<EmployeeRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.employee.hire_date</code>.
     */
    public final TableField<EmployeeRecord, LocalDate> HIRE_DATE = createField(DSL.name("hire_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.employee.name</code>.
     */
    public final TableField<EmployeeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.employee.phone</code>.
     */
    public final TableField<EmployeeRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.employee.position_code</code>.
     */
    public final TableField<EmployeeRecord, String> POSITION_CODE = createField(DSL.name("position_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.employee.sort_order</code>.
     */
    public final TableField<EmployeeRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.employee.use_yn</code>.
     */
    public final TableField<EmployeeRecord, Boolean> USE_YN = createField(DSL.name("use_yn"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Employee(Name alias, Table<EmployeeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employee(Name alias, Table<EmployeeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.employee</code> table reference
     */
    public Employee(String alias) {
        this(DSL.name(alias), EMPLOYEE);
    }

    /**
     * Create an aliased <code>public.employee</code> table reference
     */
    public Employee(Name alias) {
        this(alias, EMPLOYEE);
    }

    /**
     * Create a <code>public.employee</code> table reference
     */
    public Employee() {
        this(DSL.name("employee"), null);
    }

    public <O extends Record> Employee(Table<O> path, ForeignKey<O, EmployeeRecord> childPath, InverseForeignKey<O, EmployeeRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeePath extends Employee implements Path<EmployeeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmployeePath(Table<O> path, ForeignKey<O, EmployeeRecord> childPath, InverseForeignKey<O, EmployeeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeePath(Name alias, Table<EmployeeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeePath as(String alias) {
            return new EmployeePath(DSL.name(alias), this);
        }

        @Override
        public EmployeePath as(Name alias) {
            return new EmployeePath(alias, this);
        }

        @Override
        public EmployeePath as(Table<?> alias) {
            return new EmployeePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmployeeRecord, Long> getIdentity() {
        return (Identity<EmployeeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmployeeRecord> getPrimaryKey() {
        return Keys.EMPLOYEE_PKEY;
    }

    @Override
    public List<UniqueKey<EmployeeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UKNBYIVU8QGMX0R7WTBPLF01GF8);
    }

    private transient QuotePath _quote;

    /**
     * Get the implicit to-many join path to the <code>public.quote</code> table
     */
    public QuotePath quote() {
        if (_quote == null)
            _quote = new QuotePath(this, null, Keys.QUOTE__FKODPO7A1F6TCCW81W7G8845R8F.getInverseKey());

        return _quote;
    }

    @Override
    public Employee as(String alias) {
        return new Employee(DSL.name(alias), this);
    }

    @Override
    public Employee as(Name alias) {
        return new Employee(alias, this);
    }

    @Override
    public Employee as(Table<?> alias) {
        return new Employee(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(String name) {
        return new Employee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(Name name) {
        return new Employee(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(Table<?> name) {
        return new Employee(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Condition condition) {
        return new Employee(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
