/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.GoodsReceiptLine.GoodsReceiptLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.GoodsReceiptRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsReceipt extends TableImpl<GoodsReceiptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.goods_receipt</code>
     */
    public static final GoodsReceipt GOODS_RECEIPT = new GoodsReceipt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsReceiptRecord> getRecordType() {
        return GoodsReceiptRecord.class;
    }

    /**
     * The column <code>public.goods_receipt.receipt_date</code>.
     */
    public final TableField<GoodsReceiptRecord, LocalDate> RECEIPT_DATE = createField(DSL.name("receipt_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt.created_at</code>.
     */
    public final TableField<GoodsReceiptRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.goods_receipt.id</code>.
     */
    public final TableField<GoodsReceiptRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.goods_receipt.partner_id</code>.
     */
    public final TableField<GoodsReceiptRecord, Long> PARTNER_ID = createField(DSL.name("partner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt.po_id</code>.
     */
    public final TableField<GoodsReceiptRecord, Long> PO_ID = createField(DSL.name("po_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.goods_receipt.updated_at</code>.
     */
    public final TableField<GoodsReceiptRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.goods_receipt.version</code>.
     */
    public final TableField<GoodsReceiptRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.goods_receipt.warehouse_id</code>.
     */
    public final TableField<GoodsReceiptRecord, Long> WAREHOUSE_ID = createField(DSL.name("warehouse_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt.status_code</code>.
     */
    public final TableField<GoodsReceiptRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt.created_by</code>.
     */
    public final TableField<GoodsReceiptRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.goods_receipt.receipt_number</code>.
     */
    public final TableField<GoodsReceiptRecord, String> RECEIPT_NUMBER = createField(DSL.name("receipt_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt.updated_by</code>.
     */
    public final TableField<GoodsReceiptRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.goods_receipt.remarks</code>.
     */
    public final TableField<GoodsReceiptRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private GoodsReceipt(Name alias, Table<GoodsReceiptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GoodsReceipt(Name alias, Table<GoodsReceiptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.goods_receipt</code> table reference
     */
    public GoodsReceipt(String alias) {
        this(DSL.name(alias), GOODS_RECEIPT);
    }

    /**
     * Create an aliased <code>public.goods_receipt</code> table reference
     */
    public GoodsReceipt(Name alias) {
        this(alias, GOODS_RECEIPT);
    }

    /**
     * Create a <code>public.goods_receipt</code> table reference
     */
    public GoodsReceipt() {
        this(DSL.name("goods_receipt"), null);
    }

    public <O extends Record> GoodsReceipt(Table<O> path, ForeignKey<O, GoodsReceiptRecord> childPath, InverseForeignKey<O, GoodsReceiptRecord> parentPath) {
        super(path, childPath, parentPath, GOODS_RECEIPT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GoodsReceiptPath extends GoodsReceipt implements Path<GoodsReceiptRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GoodsReceiptPath(Table<O> path, ForeignKey<O, GoodsReceiptRecord> childPath, InverseForeignKey<O, GoodsReceiptRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GoodsReceiptPath(Name alias, Table<GoodsReceiptRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GoodsReceiptPath as(String alias) {
            return new GoodsReceiptPath(DSL.name(alias), this);
        }

        @Override
        public GoodsReceiptPath as(Name alias) {
            return new GoodsReceiptPath(alias, this);
        }

        @Override
        public GoodsReceiptPath as(Table<?> alias) {
            return new GoodsReceiptPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GoodsReceiptRecord, Long> getIdentity() {
        return (Identity<GoodsReceiptRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GoodsReceiptRecord> getPrimaryKey() {
        return Keys.GOODS_RECEIPT_PKEY;
    }

    @Override
    public List<UniqueKey<GoodsReceiptRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GOODS_RECEIPT_RECEIPT_NUMBER_KEY);
    }

    private transient GoodsReceiptLinePath _goodsReceiptLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.goods_receipt_line</code> table
     */
    public GoodsReceiptLinePath goodsReceiptLine() {
        if (_goodsReceiptLine == null)
            _goodsReceiptLine = new GoodsReceiptLinePath(this, null, Keys.GOODS_RECEIPT_LINE__FKFF5SCXF5VGRISTHDLEQKHH0P.getInverseKey());

        return _goodsReceiptLine;
    }

    @Override
    public List<Check<GoodsReceiptRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("goods_receipt_status_code_check"), "(((status_code)::text = ANY ((ARRAY['GR_STATUS_01'::character varying, 'GR_STATUS_02'::character varying, 'GR_STATUS_03'::character varying])::text[])))", true)
        );
    }

    @Override
    public GoodsReceipt as(String alias) {
        return new GoodsReceipt(DSL.name(alias), this);
    }

    @Override
    public GoodsReceipt as(Name alias) {
        return new GoodsReceipt(alias, this);
    }

    @Override
    public GoodsReceipt as(Table<?> alias) {
        return new GoodsReceipt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceipt rename(String name) {
        return new GoodsReceipt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceipt rename(Name name) {
        return new GoodsReceipt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceipt rename(Table<?> name) {
        return new GoodsReceipt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt where(Condition condition) {
        return new GoodsReceipt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceipt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceipt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceipt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceipt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceipt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
