/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.GoodsReceipt.GoodsReceiptPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.GoodsReceiptLineRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsReceiptLine extends TableImpl<GoodsReceiptLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.goods_receipt_line</code>
     */
    public static final GoodsReceiptLine GOODS_RECEIPT_LINE = new GoodsReceiptLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsReceiptLineRecord> getRecordType() {
        return GoodsReceiptLineRecord.class;
    }

    /**
     * The column <code>public.goods_receipt_line.received_quantity</code>.
     */
    public final TableField<GoodsReceiptLineRecord, BigDecimal> RECEIVED_QUANTITY = createField(DSL.name("received_quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt_line.sort_order</code>.
     */
    public final TableField<GoodsReceiptLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt_line.unit_price</code>.
     */
    public final TableField<GoodsReceiptLineRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>public.goods_receipt_line.goods_receipt_id</code>.
     */
    public final TableField<GoodsReceiptLineRecord, Long> GOODS_RECEIPT_ID = createField(DSL.name("goods_receipt_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt_line.id</code>.
     */
    public final TableField<GoodsReceiptLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.goods_receipt_line.item_id</code>.
     */
    public final TableField<GoodsReceiptLineRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt_line.po_line_id</code>.
     */
    public final TableField<GoodsReceiptLineRecord, Long> PO_LINE_ID = createField(DSL.name("po_line_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.goods_receipt_line.receipt_type_code</code>.
     */
    public final TableField<GoodsReceiptLineRecord, String> RECEIPT_TYPE_CODE = createField(DSL.name("receipt_type_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.goods_receipt_line.remarks</code>.
     */
    public final TableField<GoodsReceiptLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private GoodsReceiptLine(Name alias, Table<GoodsReceiptLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GoodsReceiptLine(Name alias, Table<GoodsReceiptLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.goods_receipt_line</code> table reference
     */
    public GoodsReceiptLine(String alias) {
        this(DSL.name(alias), GOODS_RECEIPT_LINE);
    }

    /**
     * Create an aliased <code>public.goods_receipt_line</code> table reference
     */
    public GoodsReceiptLine(Name alias) {
        this(alias, GOODS_RECEIPT_LINE);
    }

    /**
     * Create a <code>public.goods_receipt_line</code> table reference
     */
    public GoodsReceiptLine() {
        this(DSL.name("goods_receipt_line"), null);
    }

    public <O extends Record> GoodsReceiptLine(Table<O> path, ForeignKey<O, GoodsReceiptLineRecord> childPath, InverseForeignKey<O, GoodsReceiptLineRecord> parentPath) {
        super(path, childPath, parentPath, GOODS_RECEIPT_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GoodsReceiptLinePath extends GoodsReceiptLine implements Path<GoodsReceiptLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GoodsReceiptLinePath(Table<O> path, ForeignKey<O, GoodsReceiptLineRecord> childPath, InverseForeignKey<O, GoodsReceiptLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GoodsReceiptLinePath(Name alias, Table<GoodsReceiptLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GoodsReceiptLinePath as(String alias) {
            return new GoodsReceiptLinePath(DSL.name(alias), this);
        }

        @Override
        public GoodsReceiptLinePath as(Name alias) {
            return new GoodsReceiptLinePath(alias, this);
        }

        @Override
        public GoodsReceiptLinePath as(Table<?> alias) {
            return new GoodsReceiptLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GoodsReceiptLineRecord, Long> getIdentity() {
        return (Identity<GoodsReceiptLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GoodsReceiptLineRecord> getPrimaryKey() {
        return Keys.GOODS_RECEIPT_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<GoodsReceiptLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GOODS_RECEIPT_LINE__FKFF5SCXF5VGRISTHDLEQKHH0P);
    }

    private transient GoodsReceiptPath _goodsReceipt;

    /**
     * Get the implicit join path to the <code>public.goods_receipt</code>
     * table.
     */
    public GoodsReceiptPath goodsReceipt() {
        if (_goodsReceipt == null)
            _goodsReceipt = new GoodsReceiptPath(this, Keys.GOODS_RECEIPT_LINE__FKFF5SCXF5VGRISTHDLEQKHH0P, null);

        return _goodsReceipt;
    }

    @Override
    public GoodsReceiptLine as(String alias) {
        return new GoodsReceiptLine(DSL.name(alias), this);
    }

    @Override
    public GoodsReceiptLine as(Name alias) {
        return new GoodsReceiptLine(alias, this);
    }

    @Override
    public GoodsReceiptLine as(Table<?> alias) {
        return new GoodsReceiptLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceiptLine rename(String name) {
        return new GoodsReceiptLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceiptLine rename(Name name) {
        return new GoodsReceiptLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsReceiptLine rename(Table<?> name) {
        return new GoodsReceiptLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine where(Condition condition) {
        return new GoodsReceiptLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceiptLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceiptLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceiptLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GoodsReceiptLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GoodsReceiptLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
