/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.InventoryTxRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryTx extends TableImpl<InventoryTxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.inventory_tx</code>
     */
    public static final InventoryTx INVENTORY_TX = new InventoryTx();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryTxRecord> getRecordType() {
        return InventoryTxRecord.class;
    }

    /**
     * The column <code>public.inventory_tx.qty_delta</code>.
     */
    public final TableField<InventoryTxRecord, BigDecimal> QTY_DELTA = createField(DSL.name("qty_delta"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.inventory_tx.tx_date</code>.
     */
    public final TableField<InventoryTxRecord, LocalDate> TX_DATE = createField(DSL.name("tx_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.inventory_tx.created_at</code>.
     */
    public final TableField<InventoryTxRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.inventory_tx.id</code>.
     */
    public final TableField<InventoryTxRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.inventory_tx.item_id</code>.
     */
    public final TableField<InventoryTxRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.inventory_tx.ref_id</code>.
     */
    public final TableField<InventoryTxRecord, Long> REF_ID = createField(DSL.name("ref_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.inventory_tx.transfer_id</code>.
     */
    public final TableField<InventoryTxRecord, Long> TRANSFER_ID = createField(DSL.name("transfer_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.inventory_tx.warehouse_id</code>.
     */
    public final TableField<InventoryTxRecord, Long> WAREHOUSE_ID = createField(DSL.name("warehouse_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.inventory_tx.ref_type</code>.
     */
    public final TableField<InventoryTxRecord, String> REF_TYPE = createField(DSL.name("ref_type"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.inventory_tx.tx_type</code>.
     */
    public final TableField<InventoryTxRecord, String> TX_TYPE = createField(DSL.name("tx_type"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.inventory_tx.created_by</code>.
     */
    public final TableField<InventoryTxRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.inventory_tx.lot_no</code>.
     */
    public final TableField<InventoryTxRecord, String> LOT_NO = createField(DSL.name("lot_no"), SQLDataType.VARCHAR(50), this, "");

    private InventoryTx(Name alias, Table<InventoryTxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryTx(Name alias, Table<InventoryTxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.inventory_tx</code> table reference
     */
    public InventoryTx(String alias) {
        this(DSL.name(alias), INVENTORY_TX);
    }

    /**
     * Create an aliased <code>public.inventory_tx</code> table reference
     */
    public InventoryTx(Name alias) {
        this(alias, INVENTORY_TX);
    }

    /**
     * Create a <code>public.inventory_tx</code> table reference
     */
    public InventoryTx() {
        this(DSL.name("inventory_tx"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InventoryTxRecord, Long> getIdentity() {
        return (Identity<InventoryTxRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InventoryTxRecord> getPrimaryKey() {
        return Keys.INVENTORY_TX_PKEY;
    }

    @Override
    public List<Check<InventoryTxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("inventory_tx_tx_type_check"), "(((tx_type)::text = ANY ((ARRAY['PURCHASE_IN'::character varying, 'MATERIAL_RESERVE'::character varying, 'MATERIAL_UNRESERVE'::character varying, 'PRODUCTION_OUT'::character varying, 'PRODUCTION_IN'::character varying, 'SALES_OUT'::character varying, 'TRANSFER_OUT'::character varying, 'TRANSFER_IN'::character varying, 'ADJUST_IN'::character varying, 'ADJUST_OUT'::character varying])::text[])))", true)
        );
    }

    @Override
    public InventoryTx as(String alias) {
        return new InventoryTx(DSL.name(alias), this);
    }

    @Override
    public InventoryTx as(Name alias) {
        return new InventoryTx(alias, this);
    }

    @Override
    public InventoryTx as(Table<?> alias) {
        return new InventoryTx(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryTx rename(String name) {
        return new InventoryTx(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryTx rename(Name name) {
        return new InventoryTx(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryTx rename(Table<?> name) {
        return new InventoryTx(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx where(Condition condition) {
        return new InventoryTx(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryTx where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryTx where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryTx where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryTx where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryTx whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
