/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.InventoryLotRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryLot extends TableImpl<InventoryLotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.inventory_lot</code>
     */
    public static final InventoryLot INVENTORY_LOT = new InventoryLot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryLotRecord> getRecordType() {
        return InventoryLotRecord.class;
    }

    /**
     * The column <code>public.inventory_lot.expiry_date</code>.
     */
    public final TableField<InventoryLotRecord, LocalDate> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.inventory_lot.qty_on_hand</code>.
     */
    public final TableField<InventoryLotRecord, BigDecimal> QTY_ON_HAND = createField(DSL.name("qty_on_hand"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.inventory_lot.qty_reserved</code>.
     */
    public final TableField<InventoryLotRecord, BigDecimal> QTY_RESERVED = createField(DSL.name("qty_reserved"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.inventory_lot.created_at</code>.
     */
    public final TableField<InventoryLotRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.inventory_lot.id</code>.
     */
    public final TableField<InventoryLotRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.inventory_lot.item_id</code>.
     */
    public final TableField<InventoryLotRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.inventory_lot.updated_at</code>.
     */
    public final TableField<InventoryLotRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.inventory_lot.version</code>.
     */
    public final TableField<InventoryLotRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.inventory_lot.warehouse_id</code>.
     */
    public final TableField<InventoryLotRecord, Long> WAREHOUSE_ID = createField(DSL.name("warehouse_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.inventory_lot.created_by</code>.
     */
    public final TableField<InventoryLotRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.inventory_lot.lot_no</code>.
     */
    public final TableField<InventoryLotRecord, String> LOT_NO = createField(DSL.name("lot_no"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.inventory_lot.updated_by</code>.
     */
    public final TableField<InventoryLotRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    private InventoryLot(Name alias, Table<InventoryLotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryLot(Name alias, Table<InventoryLotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.inventory_lot</code> table reference
     */
    public InventoryLot(String alias) {
        this(DSL.name(alias), INVENTORY_LOT);
    }

    /**
     * Create an aliased <code>public.inventory_lot</code> table reference
     */
    public InventoryLot(Name alias) {
        this(alias, INVENTORY_LOT);
    }

    /**
     * Create a <code>public.inventory_lot</code> table reference
     */
    public InventoryLot() {
        this(DSL.name("inventory_lot"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InventoryLotRecord, Long> getIdentity() {
        return (Identity<InventoryLotRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InventoryLotRecord> getPrimaryKey() {
        return Keys.INVENTORY_LOT_PKEY;
    }

    @Override
    public List<UniqueKey<InventoryLotRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.INVENTORY_LOT_WAREHOUSE_ID_ITEM_ID_LOT_NO_KEY);
    }

    @Override
    public InventoryLot as(String alias) {
        return new InventoryLot(DSL.name(alias), this);
    }

    @Override
    public InventoryLot as(Name alias) {
        return new InventoryLot(alias, this);
    }

    @Override
    public InventoryLot as(Table<?> alias) {
        return new InventoryLot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryLot rename(String name) {
        return new InventoryLot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryLot rename(Name name) {
        return new InventoryLot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryLot rename(Table<?> name) {
        return new InventoryLot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot where(Condition condition) {
        return new InventoryLot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryLot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryLot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryLot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryLot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryLot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
