/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteLine.QuoteLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrderLine.SalesOrderLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ItemRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Item extends TableImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item</code>
     */
    public static final Item ITEM = new Item();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemRecord> getRecordType() {
        return ItemRecord.class;
    }

    /**
     * The column <code>public.item.id</code>.
     */
    public final TableField<ItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.item.code</code>.
     */
    public final TableField<ItemRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.item.description</code>.
     */
    public final TableField<ItemRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.item.item_type_code</code>.
     */
    public final TableField<ItemRecord, String> ITEM_TYPE_CODE = createField(DSL.name("item_type_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.item.name</code>.
     */
    public final TableField<ItemRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.item.sort_order</code>.
     */
    public final TableField<ItemRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.item.spec</code>.
     */
    public final TableField<ItemRecord, String> SPEC = createField(DSL.name("spec"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.item.unit</code>.
     */
    public final TableField<ItemRecord, String> UNIT = createField(DSL.name("unit"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.item.use_yn</code>.
     */
    public final TableField<ItemRecord, Boolean> USE_YN = createField(DSL.name("use_yn"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Item(Name alias, Table<ItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Item(Name alias, Table<ItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.item</code> table reference
     */
    public Item(String alias) {
        this(DSL.name(alias), ITEM);
    }

    /**
     * Create an aliased <code>public.item</code> table reference
     */
    public Item(Name alias) {
        this(alias, ITEM);
    }

    /**
     * Create a <code>public.item</code> table reference
     */
    public Item() {
        this(DSL.name("item"), null);
    }

    public <O extends Record> Item(Table<O> path, ForeignKey<O, ItemRecord> childPath, InverseForeignKey<O, ItemRecord> parentPath) {
        super(path, childPath, parentPath, ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemPath extends Item implements Path<ItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemPath(Table<O> path, ForeignKey<O, ItemRecord> childPath, InverseForeignKey<O, ItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemPath(Name alias, Table<ItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemPath as(String alias) {
            return new ItemPath(DSL.name(alias), this);
        }

        @Override
        public ItemPath as(Name alias) {
            return new ItemPath(alias, this);
        }

        @Override
        public ItemPath as(Table<?> alias) {
            return new ItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ItemRecord, Long> getIdentity() {
        return (Identity<ItemRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ItemRecord> getPrimaryKey() {
        return Keys.ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<ItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK6CGOGDARKQ48DLG1LBNV4Q1OQ);
    }

    private transient QuoteLinePath _quoteLine;

    /**
     * Get the implicit to-many join path to the <code>public.quote_line</code>
     * table
     */
    public QuoteLinePath quoteLine() {
        if (_quoteLine == null)
            _quoteLine = new QuoteLinePath(this, null, Keys.QUOTE_LINE__FKJ26RAJPBGQ93FD2VDRP775T8A.getInverseKey());

        return _quoteLine;
    }

    private transient SalesOrderLinePath _salesOrderLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.sales_order_line</code> table
     */
    public SalesOrderLinePath salesOrderLine() {
        if (_salesOrderLine == null)
            _salesOrderLine = new SalesOrderLinePath(this, null, Keys.SALES_ORDER_LINE__FKSX78NRSMY3OC216VK4KTMY1L9.getInverseKey());

        return _salesOrderLine;
    }

    @Override
    public Item as(String alias) {
        return new Item(DSL.name(alias), this);
    }

    @Override
    public Item as(Name alias) {
        return new Item(alias, this);
    }

    @Override
    public Item as(Table<?> alias) {
        return new Item(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(String name) {
        return new Item(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(Name name) {
        return new Item(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(Table<?> name) {
        return new Item(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Condition condition) {
        return new Item(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
