/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ItemPriceRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemPrice extends TableImpl<ItemPriceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item_price</code>
     */
    public static final ItemPrice ITEM_PRICE = new ItemPrice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemPriceRecord> getRecordType() {
        return ItemPriceRecord.class;
    }

    /**
     * The column <code>public.item_price.unit_price</code>.
     */
    public final TableField<ItemPriceRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 2).nullable(false), this, "");

    /**
     * The column <code>public.item_price.created_at</code>.
     */
    public final TableField<ItemPriceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.item_price.id</code>.
     */
    public final TableField<ItemPriceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.item_price.item_id</code>.
     */
    public final TableField<ItemPriceRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.item_price.updated_at</code>.
     */
    public final TableField<ItemPriceRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.item_price.version</code>.
     */
    public final TableField<ItemPriceRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.item_price.created_by</code>.
     */
    public final TableField<ItemPriceRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.item_price.updated_by</code>.
     */
    public final TableField<ItemPriceRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.item_price.remarks</code>.
     */
    public final TableField<ItemPriceRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private ItemPrice(Name alias, Table<ItemPriceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemPrice(Name alias, Table<ItemPriceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.item_price</code> table reference
     */
    public ItemPrice(String alias) {
        this(DSL.name(alias), ITEM_PRICE);
    }

    /**
     * Create an aliased <code>public.item_price</code> table reference
     */
    public ItemPrice(Name alias) {
        this(alias, ITEM_PRICE);
    }

    /**
     * Create a <code>public.item_price</code> table reference
     */
    public ItemPrice() {
        this(DSL.name("item_price"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ItemPriceRecord, Long> getIdentity() {
        return (Identity<ItemPriceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ItemPriceRecord> getPrimaryKey() {
        return Keys.ITEM_PRICE_PKEY;
    }

    @Override
    public List<UniqueKey<ItemPriceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ITEM_PRICE_ITEM_ID_KEY);
    }

    @Override
    public ItemPrice as(String alias) {
        return new ItemPrice(DSL.name(alias), this);
    }

    @Override
    public ItemPrice as(Name alias) {
        return new ItemPrice(alias, this);
    }

    @Override
    public ItemPrice as(Table<?> alias) {
        return new ItemPrice(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemPrice rename(String name) {
        return new ItemPrice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemPrice rename(Name name) {
        return new ItemPrice(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemPrice rename(Table<?> name) {
        return new ItemPrice(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice where(Condition condition) {
        return new ItemPrice(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemPrice where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemPrice where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemPrice where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemPrice where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemPrice whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
