/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PartnerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Partner extends TableImpl<PartnerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.partner</code>
     */
    public static final Partner PARTNER = new Partner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartnerRecord> getRecordType() {
        return PartnerRecord.class;
    }

    /**
     * The column <code>public.partner.created_at</code>.
     */
    public final TableField<PartnerRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.partner.id</code>.
     */
    public final TableField<PartnerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.partner.updated_at</code>.
     */
    public final TableField<PartnerRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.partner.version</code>.
     */
    public final TableField<PartnerRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.partner.business_number</code>.
     */
    public final TableField<PartnerRecord, String> BUSINESS_NUMBER = createField(DSL.name("business_number"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.partner.phone1</code>.
     */
    public final TableField<PartnerRecord, String> PHONE1 = createField(DSL.name("phone1"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.partner.phone2</code>.
     */
    public final TableField<PartnerRecord, String> PHONE2 = createField(DSL.name("phone2"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.partner.trade_type_code</code>.
     */
    public final TableField<PartnerRecord, String> TRADE_TYPE_CODE = createField(DSL.name("trade_type_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.partner.ceo_name</code>.
     */
    public final TableField<PartnerRecord, String> CEO_NAME = createField(DSL.name("ceo_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.partner.code</code>.
     */
    public final TableField<PartnerRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.partner.created_by</code>.
     */
    public final TableField<PartnerRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.partner.updated_by</code>.
     */
    public final TableField<PartnerRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.partner.name</code>.
     */
    public final TableField<PartnerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.partner.address</code>.
     */
    public final TableField<PartnerRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(200), this, "");

    private Partner(Name alias, Table<PartnerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Partner(Name alias, Table<PartnerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.partner</code> table reference
     */
    public Partner(String alias) {
        this(DSL.name(alias), PARTNER);
    }

    /**
     * Create an aliased <code>public.partner</code> table reference
     */
    public Partner(Name alias) {
        this(alias, PARTNER);
    }

    /**
     * Create a <code>public.partner</code> table reference
     */
    public Partner() {
        this(DSL.name("partner"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PartnerRecord, Long> getIdentity() {
        return (Identity<PartnerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PartnerRecord> getPrimaryKey() {
        return Keys.PARTNER_PKEY;
    }

    @Override
    public List<UniqueKey<PartnerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PARTNER_CODE_KEY);
    }

    @Override
    public Partner as(String alias) {
        return new Partner(DSL.name(alias), this);
    }

    @Override
    public Partner as(Name alias) {
        return new Partner(alias, this);
    }

    @Override
    public Partner as(Table<?> alias) {
        return new Partner(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Partner rename(String name) {
        return new Partner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partner rename(Name name) {
        return new Partner(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partner rename(Table<?> name) {
        return new Partner(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner where(Condition condition) {
        return new Partner(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partner where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partner where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partner where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partner where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partner whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
