/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseRequestLine.PurchaseRequestLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseRequestRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRequest extends TableImpl<PurchaseRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purchase_request</code>
     */
    public static final PurchaseRequest PURCHASE_REQUEST = new PurchaseRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseRequestRecord> getRecordType() {
        return PurchaseRequestRecord.class;
    }

    /**
     * The column <code>public.purchase_request.request_date</code>.
     */
    public final TableField<PurchaseRequestRecord, LocalDate> REQUEST_DATE = createField(DSL.name("request_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.purchase_request.created_at</code>.
     */
    public final TableField<PurchaseRequestRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.purchase_request.id</code>.
     */
    public final TableField<PurchaseRequestRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.purchase_request.requester_id</code>.
     */
    public final TableField<PurchaseRequestRecord, Long> REQUESTER_ID = createField(DSL.name("requester_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.purchase_request.updated_at</code>.
     */
    public final TableField<PurchaseRequestRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.purchase_request.version</code>.
     */
    public final TableField<PurchaseRequestRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.purchase_request.status_code</code>.
     */
    public final TableField<PurchaseRequestRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.purchase_request.created_by</code>.
     */
    public final TableField<PurchaseRequestRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.purchase_request.request_number</code>.
     */
    public final TableField<PurchaseRequestRecord, String> REQUEST_NUMBER = createField(DSL.name("request_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.purchase_request.updated_by</code>.
     */
    public final TableField<PurchaseRequestRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.purchase_request.remarks</code>.
     */
    public final TableField<PurchaseRequestRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private PurchaseRequest(Name alias, Table<PurchaseRequestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurchaseRequest(Name alias, Table<PurchaseRequestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest(String alias) {
        this(DSL.name(alias), PURCHASE_REQUEST);
    }

    /**
     * Create an aliased <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest(Name alias) {
        this(alias, PURCHASE_REQUEST);
    }

    /**
     * Create a <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest() {
        this(DSL.name("purchase_request"), null);
    }

    public <O extends Record> PurchaseRequest(Table<O> path, ForeignKey<O, PurchaseRequestRecord> childPath, InverseForeignKey<O, PurchaseRequestRecord> parentPath) {
        super(path, childPath, parentPath, PURCHASE_REQUEST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PurchaseRequestPath extends PurchaseRequest implements Path<PurchaseRequestRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PurchaseRequestPath(Table<O> path, ForeignKey<O, PurchaseRequestRecord> childPath, InverseForeignKey<O, PurchaseRequestRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PurchaseRequestPath(Name alias, Table<PurchaseRequestRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PurchaseRequestPath as(String alias) {
            return new PurchaseRequestPath(DSL.name(alias), this);
        }

        @Override
        public PurchaseRequestPath as(Name alias) {
            return new PurchaseRequestPath(alias, this);
        }

        @Override
        public PurchaseRequestPath as(Table<?> alias) {
            return new PurchaseRequestPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PurchaseRequestRecord, Long> getIdentity() {
        return (Identity<PurchaseRequestRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PurchaseRequestRecord> getPrimaryKey() {
        return Keys.PURCHASE_REQUEST_PKEY;
    }

    @Override
    public List<UniqueKey<PurchaseRequestRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PURCHASE_REQUEST_REQUEST_NUMBER_KEY);
    }

    private transient PurchaseRequestLinePath _purchaseRequestLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.purchase_request_line</code> table
     */
    public PurchaseRequestLinePath purchaseRequestLine() {
        if (_purchaseRequestLine == null)
            _purchaseRequestLine = new PurchaseRequestLinePath(this, null, Keys.PURCHASE_REQUEST_LINE__FKM11FJM2MHKX5C3XJL7H3K3137.getInverseKey());

        return _purchaseRequestLine;
    }

    @Override
    public List<Check<PurchaseRequestRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("purchase_request_status_code_check"), "(((status_code)::text = ANY ((ARRAY['PR_STATUS_01'::character varying, 'PR_STATUS_03'::character varying, 'PR_STATUS_02'::character varying, 'PR_STATUS_05'::character varying, 'PR_STATUS_04'::character varying])::text[])))", true)
        );
    }

    @Override
    public PurchaseRequest as(String alias) {
        return new PurchaseRequest(DSL.name(alias), this);
    }

    @Override
    public PurchaseRequest as(Name alias) {
        return new PurchaseRequest(alias, this);
    }

    @Override
    public PurchaseRequest as(Table<?> alias) {
        return new PurchaseRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(String name) {
        return new PurchaseRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(Name name) {
        return new PurchaseRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(Table<?> name) {
        return new PurchaseRequest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest where(Condition condition) {
        return new PurchaseRequest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseRequest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseRequest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseRequest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseRequest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseRequest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
