/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseOrder.PurchaseOrderPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseOrderLineRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrderLine extends TableImpl<PurchaseOrderLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purchase_order_line</code>
     */
    public static final PurchaseOrderLine PURCHASE_ORDER_LINE = new PurchaseOrderLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseOrderLineRecord> getRecordType() {
        return PurchaseOrderLineRecord.class;
    }

    /**
     * The column <code>public.purchase_order_line.ordered_quantity</code>.
     */
    public final TableField<PurchaseOrderLineRecord, BigDecimal> ORDERED_QUANTITY = createField(DSL.name("ordered_quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.purchase_order_line.required_date</code>.
     */
    public final TableField<PurchaseOrderLineRecord, LocalDate> REQUIRED_DATE = createField(DSL.name("required_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.purchase_order_line.sort_order</code>.
     */
    public final TableField<PurchaseOrderLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order_line.unit_price</code>.
     */
    public final TableField<PurchaseOrderLineRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>public.purchase_order_line.id</code>.
     */
    public final TableField<PurchaseOrderLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.purchase_order_line.item_id</code>.
     */
    public final TableField<PurchaseOrderLineRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order_line.pr_line_id</code>.
     */
    public final TableField<PurchaseOrderLineRecord, Long> PR_LINE_ID = createField(DSL.name("pr_line_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.purchase_order_line.purchase_order_id</code>.
     */
    public final TableField<PurchaseOrderLineRecord, Long> PURCHASE_ORDER_ID = createField(DSL.name("purchase_order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order_line.remarks</code>.
     */
    public final TableField<PurchaseOrderLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private PurchaseOrderLine(Name alias, Table<PurchaseOrderLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurchaseOrderLine(Name alias, Table<PurchaseOrderLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purchase_order_line</code> table reference
     */
    public PurchaseOrderLine(String alias) {
        this(DSL.name(alias), PURCHASE_ORDER_LINE);
    }

    /**
     * Create an aliased <code>public.purchase_order_line</code> table reference
     */
    public PurchaseOrderLine(Name alias) {
        this(alias, PURCHASE_ORDER_LINE);
    }

    /**
     * Create a <code>public.purchase_order_line</code> table reference
     */
    public PurchaseOrderLine() {
        this(DSL.name("purchase_order_line"), null);
    }

    public <O extends Record> PurchaseOrderLine(Table<O> path, ForeignKey<O, PurchaseOrderLineRecord> childPath, InverseForeignKey<O, PurchaseOrderLineRecord> parentPath) {
        super(path, childPath, parentPath, PURCHASE_ORDER_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PurchaseOrderLinePath extends PurchaseOrderLine implements Path<PurchaseOrderLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PurchaseOrderLinePath(Table<O> path, ForeignKey<O, PurchaseOrderLineRecord> childPath, InverseForeignKey<O, PurchaseOrderLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PurchaseOrderLinePath(Name alias, Table<PurchaseOrderLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PurchaseOrderLinePath as(String alias) {
            return new PurchaseOrderLinePath(DSL.name(alias), this);
        }

        @Override
        public PurchaseOrderLinePath as(Name alias) {
            return new PurchaseOrderLinePath(alias, this);
        }

        @Override
        public PurchaseOrderLinePath as(Table<?> alias) {
            return new PurchaseOrderLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PurchaseOrderLineRecord, Long> getIdentity() {
        return (Identity<PurchaseOrderLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PurchaseOrderLineRecord> getPrimaryKey() {
        return Keys.PURCHASE_ORDER_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<PurchaseOrderLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PURCHASE_ORDER_LINE__FK210T80FSGDI4S4G7TLG9VDGKD);
    }

    private transient PurchaseOrderPath _purchaseOrder;

    /**
     * Get the implicit join path to the <code>public.purchase_order</code>
     * table.
     */
    public PurchaseOrderPath purchaseOrder() {
        if (_purchaseOrder == null)
            _purchaseOrder = new PurchaseOrderPath(this, Keys.PURCHASE_ORDER_LINE__FK210T80FSGDI4S4G7TLG9VDGKD, null);

        return _purchaseOrder;
    }

    @Override
    public PurchaseOrderLine as(String alias) {
        return new PurchaseOrderLine(DSL.name(alias), this);
    }

    @Override
    public PurchaseOrderLine as(Name alias) {
        return new PurchaseOrderLine(alias, this);
    }

    @Override
    public PurchaseOrderLine as(Table<?> alias) {
        return new PurchaseOrderLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrderLine rename(String name) {
        return new PurchaseOrderLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrderLine rename(Name name) {
        return new PurchaseOrderLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrderLine rename(Table<?> name) {
        return new PurchaseOrderLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine where(Condition condition) {
        return new PurchaseOrderLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrderLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrderLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrderLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrderLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrderLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
