/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.PurchaseOrderLine.PurchaseOrderLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.PurchaseOrderRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrder extends TableImpl<PurchaseOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purchase_order</code>
     */
    public static final PurchaseOrder PURCHASE_ORDER = new PurchaseOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseOrderRecord> getRecordType() {
        return PurchaseOrderRecord.class;
    }

    /**
     * The column <code>public.purchase_order.expected_arrival_date</code>.
     */
    public final TableField<PurchaseOrderRecord, LocalDate> EXPECTED_ARRIVAL_DATE = createField(DSL.name("expected_arrival_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.purchase_order.order_date</code>.
     */
    public final TableField<PurchaseOrderRecord, LocalDate> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.created_at</code>.
     */
    public final TableField<PurchaseOrderRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.purchase_order.id</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.purchase_order.partner_id</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> PARTNER_ID = createField(DSL.name("partner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.pr_id</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> PR_ID = createField(DSL.name("pr_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.purchase_order.updated_at</code>.
     */
    public final TableField<PurchaseOrderRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.purchase_order.version</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.purchase_order.status_code</code>.
     */
    public final TableField<PurchaseOrderRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.created_by</code>.
     */
    public final TableField<PurchaseOrderRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.purchase_order.order_number</code>.
     */
    public final TableField<PurchaseOrderRecord, String> ORDER_NUMBER = createField(DSL.name("order_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.updated_by</code>.
     */
    public final TableField<PurchaseOrderRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.purchase_order.remarks</code>.
     */
    public final TableField<PurchaseOrderRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private PurchaseOrder(Name alias, Table<PurchaseOrderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurchaseOrder(Name alias, Table<PurchaseOrderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder(String alias) {
        this(DSL.name(alias), PURCHASE_ORDER);
    }

    /**
     * Create an aliased <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder(Name alias) {
        this(alias, PURCHASE_ORDER);
    }

    /**
     * Create a <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder() {
        this(DSL.name("purchase_order"), null);
    }

    public <O extends Record> PurchaseOrder(Table<O> path, ForeignKey<O, PurchaseOrderRecord> childPath, InverseForeignKey<O, PurchaseOrderRecord> parentPath) {
        super(path, childPath, parentPath, PURCHASE_ORDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PurchaseOrderPath extends PurchaseOrder implements Path<PurchaseOrderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PurchaseOrderPath(Table<O> path, ForeignKey<O, PurchaseOrderRecord> childPath, InverseForeignKey<O, PurchaseOrderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PurchaseOrderPath(Name alias, Table<PurchaseOrderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PurchaseOrderPath as(String alias) {
            return new PurchaseOrderPath(DSL.name(alias), this);
        }

        @Override
        public PurchaseOrderPath as(Name alias) {
            return new PurchaseOrderPath(alias, this);
        }

        @Override
        public PurchaseOrderPath as(Table<?> alias) {
            return new PurchaseOrderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PurchaseOrderRecord, Long> getIdentity() {
        return (Identity<PurchaseOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PurchaseOrderRecord> getPrimaryKey() {
        return Keys.PURCHASE_ORDER_PKEY;
    }

    @Override
    public List<UniqueKey<PurchaseOrderRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PURCHASE_ORDER_ORDER_NUMBER_KEY);
    }

    private transient PurchaseOrderLinePath _purchaseOrderLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.purchase_order_line</code> table
     */
    public PurchaseOrderLinePath purchaseOrderLine() {
        if (_purchaseOrderLine == null)
            _purchaseOrderLine = new PurchaseOrderLinePath(this, null, Keys.PURCHASE_ORDER_LINE__FK210T80FSGDI4S4G7TLG9VDGKD.getInverseKey());

        return _purchaseOrderLine;
    }

    @Override
    public List<Check<PurchaseOrderRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("purchase_order_status_code_check"), "(((status_code)::text = ANY ((ARRAY['PO_STATUS_02'::character varying, 'PO_STATUS_01'::character varying, 'PO_STATUS_04'::character varying, 'PO_STATUS_03'::character varying])::text[])))", true)
        );
    }

    @Override
    public PurchaseOrder as(String alias) {
        return new PurchaseOrder(DSL.name(alias), this);
    }

    @Override
    public PurchaseOrder as(Name alias) {
        return new PurchaseOrder(alias, this);
    }

    @Override
    public PurchaseOrder as(Table<?> alias) {
        return new PurchaseOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(String name) {
        return new PurchaseOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(Name name) {
        return new PurchaseOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(Table<?> name) {
        return new PurchaseOrder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Condition condition) {
        return new PurchaseOrder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
