/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteApprovalRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuoteApproval extends TableImpl<QuoteApprovalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quote_approval</code>
     */
    public static final QuoteApproval QUOTE_APPROVAL = new QuoteApproval();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuoteApprovalRecord> getRecordType() {
        return QuoteApprovalRecord.class;
    }

    /**
     * The column <code>public.quote_approval.id</code>.
     */
    public final TableField<QuoteApprovalRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.quote_approval.action</code>.
     */
    public final TableField<QuoteApprovalRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.quote_approval.approver_employee_id</code>.
     */
    public final TableField<QuoteApprovalRecord, Long> APPROVER_EMPLOYEE_ID = createField(DSL.name("approver_employee_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.quote_approval.approver_name</code>.
     */
    public final TableField<QuoteApprovalRecord, String> APPROVER_NAME = createField(DSL.name("approver_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.quote_approval.approver_username</code>.
     */
    public final TableField<QuoteApprovalRecord, String> APPROVER_USERNAME = createField(DSL.name("approver_username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.quote_approval.comment</code>.
     */
    public final TableField<QuoteApprovalRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.quote_approval.created_at</code>.
     */
    public final TableField<QuoteApprovalRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.quote_approval.quote_id</code>.
     */
    public final TableField<QuoteApprovalRecord, Long> QUOTE_ID = createField(DSL.name("quote_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private QuoteApproval(Name alias, Table<QuoteApprovalRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private QuoteApproval(Name alias, Table<QuoteApprovalRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quote_approval</code> table reference
     */
    public QuoteApproval(String alias) {
        this(DSL.name(alias), QUOTE_APPROVAL);
    }

    /**
     * Create an aliased <code>public.quote_approval</code> table reference
     */
    public QuoteApproval(Name alias) {
        this(alias, QUOTE_APPROVAL);
    }

    /**
     * Create a <code>public.quote_approval</code> table reference
     */
    public QuoteApproval() {
        this(DSL.name("quote_approval"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<QuoteApprovalRecord, Long> getIdentity() {
        return (Identity<QuoteApprovalRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QuoteApprovalRecord> getPrimaryKey() {
        return Keys.QUOTE_APPROVAL_PKEY;
    }

    @Override
    public QuoteApproval as(String alias) {
        return new QuoteApproval(DSL.name(alias), this);
    }

    @Override
    public QuoteApproval as(Name alias) {
        return new QuoteApproval(alias, this);
    }

    @Override
    public QuoteApproval as(Table<?> alias) {
        return new QuoteApproval(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuoteApproval rename(String name) {
        return new QuoteApproval(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuoteApproval rename(Name name) {
        return new QuoteApproval(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuoteApproval rename(Table<?> name) {
        return new QuoteApproval(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval where(Condition condition) {
        return new QuoteApproval(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuoteApproval where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuoteApproval where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuoteApproval where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public QuoteApproval where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public QuoteApproval whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
