/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Employee.EmployeePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.Partner.PartnerPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.QuoteLine.QuoteLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.QuoteRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quote extends TableImpl<QuoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.quote</code>
     */
    public static final Quote QUOTE = new Quote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuoteRecord> getRecordType() {
        return QuoteRecord.class;
    }

    /**
     * The column <code>public.quote.id</code>.
     */
    public final TableField<QuoteRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.quote.quote_date</code>.
     */
    public final TableField<QuoteRecord, LocalDate> QUOTE_DATE = createField(DSL.name("quote_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.quote.quote_number</code>.
     */
    public final TableField<QuoteRecord, String> QUOTE_NUMBER = createField(DSL.name("quote_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.quote.remarks</code>.
     */
    public final TableField<QuoteRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.quote.status_code</code>.
     */
    public final TableField<QuoteRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.quote.valid_until</code>.
     */
    public final TableField<QuoteRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.quote.employee_id</code>.
     */
    public final TableField<QuoteRecord, Long> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.quote.partner_id</code>.
     */
    public final TableField<QuoteRecord, Long> PARTNER_ID = createField(DSL.name("partner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Quote(Name alias, Table<QuoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Quote(Name alias, Table<QuoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.quote</code> table reference
     */
    public Quote(String alias) {
        this(DSL.name(alias), QUOTE);
    }

    /**
     * Create an aliased <code>public.quote</code> table reference
     */
    public Quote(Name alias) {
        this(alias, QUOTE);
    }

    /**
     * Create a <code>public.quote</code> table reference
     */
    public Quote() {
        this(DSL.name("quote"), null);
    }

    public <O extends Record> Quote(Table<O> path, ForeignKey<O, QuoteRecord> childPath, InverseForeignKey<O, QuoteRecord> parentPath) {
        super(path, childPath, parentPath, QUOTE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class QuotePath extends Quote implements Path<QuoteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> QuotePath(Table<O> path, ForeignKey<O, QuoteRecord> childPath, InverseForeignKey<O, QuoteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private QuotePath(Name alias, Table<QuoteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public QuotePath as(String alias) {
            return new QuotePath(DSL.name(alias), this);
        }

        @Override
        public QuotePath as(Name alias) {
            return new QuotePath(alias, this);
        }

        @Override
        public QuotePath as(Table<?> alias) {
            return new QuotePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<QuoteRecord, Long> getIdentity() {
        return (Identity<QuoteRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QuoteRecord> getPrimaryKey() {
        return Keys.QUOTE_PKEY;
    }

    @Override
    public List<UniqueKey<QuoteRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UKC6L8KA84HB9DFDG5PKHT3FA79);
    }

    @Override
    public List<ForeignKey<QuoteRecord, ?>> getReferences() {
        return Arrays.asList(Keys.QUOTE__FK9ALFG10RCMMPSCETID6LB5OOT, Keys.QUOTE__FKODPO7A1F6TCCW81W7G8845R8F);
    }

    private transient PartnerPath _partner;

    /**
     * Get the implicit join path to the <code>public.partner</code> table.
     */
    public PartnerPath partner() {
        if (_partner == null)
            _partner = new PartnerPath(this, Keys.QUOTE__FK9ALFG10RCMMPSCETID6LB5OOT, null);

        return _partner;
    }

    private transient EmployeePath _employee;

    /**
     * Get the implicit join path to the <code>public.employee</code> table.
     */
    public EmployeePath employee() {
        if (_employee == null)
            _employee = new EmployeePath(this, Keys.QUOTE__FKODPO7A1F6TCCW81W7G8845R8F, null);

        return _employee;
    }

    private transient QuoteLinePath _quoteLine;

    /**
     * Get the implicit to-many join path to the <code>public.quote_line</code>
     * table
     */
    public QuoteLinePath quoteLine() {
        if (_quoteLine == null)
            _quoteLine = new QuoteLinePath(this, null, Keys.QUOTE_LINE__FKNBXR28WOT0665O7O2FGY4H0XR.getInverseKey());

        return _quoteLine;
    }

    @Override
    public Quote as(String alias) {
        return new Quote(DSL.name(alias), this);
    }

    @Override
    public Quote as(Name alias) {
        return new Quote(alias, this);
    }

    @Override
    public Quote as(Table<?> alias) {
        return new Quote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Quote rename(String name) {
        return new Quote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Quote rename(Name name) {
        return new Quote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Quote rename(Table<?> name) {
        return new Quote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote where(Condition condition) {
        return new Quote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Quote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Quote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Quote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Quote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Quote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
