/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.RevenueLine.RevenueLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RevenueRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Revenue extends TableImpl<RevenueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.revenue</code>
     */
    public static final Revenue REVENUE = new Revenue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RevenueRecord> getRecordType() {
        return RevenueRecord.class;
    }

    /**
     * The column <code>public.revenue.revenue_date</code>.
     */
    public final TableField<RevenueRecord, LocalDate> REVENUE_DATE = createField(DSL.name("revenue_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.revenue.created_at</code>.
     */
    public final TableField<RevenueRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.revenue.employee_id</code>.
     */
    public final TableField<RevenueRecord, Long> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.revenue.id</code>.
     */
    public final TableField<RevenueRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.revenue.partner_id</code>.
     */
    public final TableField<RevenueRecord, Long> PARTNER_ID = createField(DSL.name("partner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.revenue.updated_at</code>.
     */
    public final TableField<RevenueRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.revenue.version</code>.
     */
    public final TableField<RevenueRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.revenue.status_code</code>.
     */
    public final TableField<RevenueRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.revenue.created_by</code>.
     */
    public final TableField<RevenueRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.revenue.revenue_number</code>.
     */
    public final TableField<RevenueRecord, String> REVENUE_NUMBER = createField(DSL.name("revenue_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.revenue.updated_by</code>.
     */
    public final TableField<RevenueRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.revenue.remarks</code>.
     */
    public final TableField<RevenueRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private Revenue(Name alias, Table<RevenueRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Revenue(Name alias, Table<RevenueRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.revenue</code> table reference
     */
    public Revenue(String alias) {
        this(DSL.name(alias), REVENUE);
    }

    /**
     * Create an aliased <code>public.revenue</code> table reference
     */
    public Revenue(Name alias) {
        this(alias, REVENUE);
    }

    /**
     * Create a <code>public.revenue</code> table reference
     */
    public Revenue() {
        this(DSL.name("revenue"), null);
    }

    public <O extends Record> Revenue(Table<O> path, ForeignKey<O, RevenueRecord> childPath, InverseForeignKey<O, RevenueRecord> parentPath) {
        super(path, childPath, parentPath, REVENUE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RevenuePath extends Revenue implements Path<RevenueRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RevenuePath(Table<O> path, ForeignKey<O, RevenueRecord> childPath, InverseForeignKey<O, RevenueRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RevenuePath(Name alias, Table<RevenueRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RevenuePath as(String alias) {
            return new RevenuePath(DSL.name(alias), this);
        }

        @Override
        public RevenuePath as(Name alias) {
            return new RevenuePath(alias, this);
        }

        @Override
        public RevenuePath as(Table<?> alias) {
            return new RevenuePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RevenueRecord, Long> getIdentity() {
        return (Identity<RevenueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RevenueRecord> getPrimaryKey() {
        return Keys.REVENUE_PKEY;
    }

    @Override
    public List<UniqueKey<RevenueRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REVENUE_REVENUE_NUMBER_KEY);
    }

    private transient RevenueLinePath _revenueLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.revenue_line</code> table
     */
    public RevenueLinePath revenueLine() {
        if (_revenueLine == null)
            _revenueLine = new RevenueLinePath(this, null, Keys.REVENUE_LINE__FKOV8M9QHYFLW6UXIWW8YYSG1WD.getInverseKey());

        return _revenueLine;
    }

    @Override
    public List<Check<RevenueRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("revenue_status_code_check"), "(((status_code)::text = ANY ((ARRAY['REVENUE_STATUS_03'::character varying, 'REVENUE_STATUS_02'::character varying, 'REVENUE_STATUS_01'::character varying])::text[])))", true)
        );
    }

    @Override
    public Revenue as(String alias) {
        return new Revenue(DSL.name(alias), this);
    }

    @Override
    public Revenue as(Name alias) {
        return new Revenue(alias, this);
    }

    @Override
    public Revenue as(Table<?> alias) {
        return new Revenue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenue rename(String name) {
        return new Revenue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenue rename(Name name) {
        return new Revenue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revenue rename(Table<?> name) {
        return new Revenue(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue where(Condition condition) {
        return new Revenue(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenue where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenue where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenue where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revenue where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revenue whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
