/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Revenue.RevenuePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RevenueLineRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevenueLine extends TableImpl<RevenueLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.revenue_line</code>
     */
    public static final RevenueLine REVENUE_LINE = new RevenueLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RevenueLineRecord> getRecordType() {
        return RevenueLineRecord.class;
    }

    /**
     * The column <code>public.revenue_line.amount</code>.
     */
    public final TableField<RevenueLineRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.quantity</code>.
     */
    public final TableField<RevenueLineRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.sort_order</code>.
     */
    public final TableField<RevenueLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.unit_price</code>.
     */
    public final TableField<RevenueLineRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.id</code>.
     */
    public final TableField<RevenueLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.revenue_line.item_id</code>.
     */
    public final TableField<RevenueLineRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.revenue_id</code>.
     */
    public final TableField<RevenueLineRecord, Long> REVENUE_ID = createField(DSL.name("revenue_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.sales_order_id</code>.
     */
    public final TableField<RevenueLineRecord, Long> SALES_ORDER_ID = createField(DSL.name("sales_order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.sales_order_line_id</code>.
     */
    public final TableField<RevenueLineRecord, Long> SALES_ORDER_LINE_ID = createField(DSL.name("sales_order_line_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.revenue_line.remarks</code>.
     */
    public final TableField<RevenueLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private RevenueLine(Name alias, Table<RevenueLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RevenueLine(Name alias, Table<RevenueLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.revenue_line</code> table reference
     */
    public RevenueLine(String alias) {
        this(DSL.name(alias), REVENUE_LINE);
    }

    /**
     * Create an aliased <code>public.revenue_line</code> table reference
     */
    public RevenueLine(Name alias) {
        this(alias, REVENUE_LINE);
    }

    /**
     * Create a <code>public.revenue_line</code> table reference
     */
    public RevenueLine() {
        this(DSL.name("revenue_line"), null);
    }

    public <O extends Record> RevenueLine(Table<O> path, ForeignKey<O, RevenueLineRecord> childPath, InverseForeignKey<O, RevenueLineRecord> parentPath) {
        super(path, childPath, parentPath, REVENUE_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RevenueLinePath extends RevenueLine implements Path<RevenueLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RevenueLinePath(Table<O> path, ForeignKey<O, RevenueLineRecord> childPath, InverseForeignKey<O, RevenueLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RevenueLinePath(Name alias, Table<RevenueLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RevenueLinePath as(String alias) {
            return new RevenueLinePath(DSL.name(alias), this);
        }

        @Override
        public RevenueLinePath as(Name alias) {
            return new RevenueLinePath(alias, this);
        }

        @Override
        public RevenueLinePath as(Table<?> alias) {
            return new RevenueLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RevenueLineRecord, Long> getIdentity() {
        return (Identity<RevenueLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RevenueLineRecord> getPrimaryKey() {
        return Keys.REVENUE_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<RevenueLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REVENUE_LINE__FKOV8M9QHYFLW6UXIWW8YYSG1WD);
    }

    private transient RevenuePath _revenue;

    /**
     * Get the implicit join path to the <code>public.revenue</code> table.
     */
    public RevenuePath revenue() {
        if (_revenue == null)
            _revenue = new RevenuePath(this, Keys.REVENUE_LINE__FKOV8M9QHYFLW6UXIWW8YYSG1WD, null);

        return _revenue;
    }

    @Override
    public RevenueLine as(String alias) {
        return new RevenueLine(DSL.name(alias), this);
    }

    @Override
    public RevenueLine as(Name alias) {
        return new RevenueLine(alias, this);
    }

    @Override
    public RevenueLine as(Table<?> alias) {
        return new RevenueLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RevenueLine rename(String name) {
        return new RevenueLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RevenueLine rename(Name name) {
        return new RevenueLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RevenueLine rename(Table<?> name) {
        return new RevenueLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine where(Condition condition) {
        return new RevenueLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RevenueLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RevenueLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RevenueLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RevenueLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RevenueLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
