/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.RoutingStep.RoutingStepPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RoutingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routing extends TableImpl<RoutingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.routing</code>
     */
    public static final Routing ROUTING = new Routing();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoutingRecord> getRecordType() {
        return RoutingRecord.class;
    }

    /**
     * The column <code>public.routing.active_yn</code>.
     */
    public final TableField<RoutingRecord, Boolean> ACTIVE_YN = createField(DSL.name("active_yn"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.routing.bom_id</code>.
     */
    public final TableField<RoutingRecord, Long> BOM_ID = createField(DSL.name("bom_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.routing.created_at</code>.
     */
    public final TableField<RoutingRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.routing.id</code>.
     */
    public final TableField<RoutingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.routing.updated_at</code>.
     */
    public final TableField<RoutingRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.routing.version</code>.
     */
    public final TableField<RoutingRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.routing.created_by</code>.
     */
    public final TableField<RoutingRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.routing.updated_by</code>.
     */
    public final TableField<RoutingRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    private Routing(Name alias, Table<RoutingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Routing(Name alias, Table<RoutingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.routing</code> table reference
     */
    public Routing(String alias) {
        this(DSL.name(alias), ROUTING);
    }

    /**
     * Create an aliased <code>public.routing</code> table reference
     */
    public Routing(Name alias) {
        this(alias, ROUTING);
    }

    /**
     * Create a <code>public.routing</code> table reference
     */
    public Routing() {
        this(DSL.name("routing"), null);
    }

    public <O extends Record> Routing(Table<O> path, ForeignKey<O, RoutingRecord> childPath, InverseForeignKey<O, RoutingRecord> parentPath) {
        super(path, childPath, parentPath, ROUTING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoutingPath extends Routing implements Path<RoutingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoutingPath(Table<O> path, ForeignKey<O, RoutingRecord> childPath, InverseForeignKey<O, RoutingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoutingPath(Name alias, Table<RoutingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoutingPath as(String alias) {
            return new RoutingPath(DSL.name(alias), this);
        }

        @Override
        public RoutingPath as(Name alias) {
            return new RoutingPath(alias, this);
        }

        @Override
        public RoutingPath as(Table<?> alias) {
            return new RoutingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RoutingRecord, Long> getIdentity() {
        return (Identity<RoutingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoutingRecord> getPrimaryKey() {
        return Keys.ROUTING_PKEY;
    }

    @Override
    public List<UniqueKey<RoutingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ROUTING_BOM_ID_KEY);
    }

    private transient RoutingStepPath _routingStep;

    /**
     * Get the implicit to-many join path to the
     * <code>public.routing_step</code> table
     */
    public RoutingStepPath routingStep() {
        if (_routingStep == null)
            _routingStep = new RoutingStepPath(this, null, Keys.ROUTING_STEP__FKS0344EWKFFWRBCEMENEEGEB9U.getInverseKey());

        return _routingStep;
    }

    @Override
    public Routing as(String alias) {
        return new Routing(DSL.name(alias), this);
    }

    @Override
    public Routing as(Name alias) {
        return new Routing(alias, this);
    }

    @Override
    public Routing as(Table<?> alias) {
        return new Routing(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Routing rename(String name) {
        return new Routing(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Routing rename(Name name) {
        return new Routing(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Routing rename(Table<?> name) {
        return new Routing(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing where(Condition condition) {
        return new Routing(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Routing where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Routing where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Routing where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Routing where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Routing whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
