/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Routing.RoutingPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.RoutingStepRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutingStep extends TableImpl<RoutingStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.routing_step</code>
     */
    public static final RoutingStep ROUTING_STEP = new RoutingStep();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoutingStepRecord> getRecordType() {
        return RoutingStepRecord.class;
    }

    /**
     * The column <code>public.routing_step.standard_time</code>.
     */
    public final TableField<RoutingStepRecord, Integer> STANDARD_TIME = createField(DSL.name("standard_time"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.routing_step.step_order</code>.
     */
    public final TableField<RoutingStepRecord, Integer> STEP_ORDER = createField(DSL.name("step_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.routing_step.created_at</code>.
     */
    public final TableField<RoutingStepRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.routing_step.id</code>.
     */
    public final TableField<RoutingStepRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.routing_step.process_id</code>.
     */
    public final TableField<RoutingStepRecord, Long> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.routing_step.routing_id</code>.
     */
    public final TableField<RoutingStepRecord, Long> ROUTING_ID = createField(DSL.name("routing_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.routing_step.updated_at</code>.
     */
    public final TableField<RoutingStepRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.routing_step.version</code>.
     */
    public final TableField<RoutingStepRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.routing_step.created_by</code>.
     */
    public final TableField<RoutingStepRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.routing_step.updated_by</code>.
     */
    public final TableField<RoutingStepRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.routing_step.remarks</code>.
     */
    public final TableField<RoutingStepRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private RoutingStep(Name alias, Table<RoutingStepRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoutingStep(Name alias, Table<RoutingStepRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.routing_step</code> table reference
     */
    public RoutingStep(String alias) {
        this(DSL.name(alias), ROUTING_STEP);
    }

    /**
     * Create an aliased <code>public.routing_step</code> table reference
     */
    public RoutingStep(Name alias) {
        this(alias, ROUTING_STEP);
    }

    /**
     * Create a <code>public.routing_step</code> table reference
     */
    public RoutingStep() {
        this(DSL.name("routing_step"), null);
    }

    public <O extends Record> RoutingStep(Table<O> path, ForeignKey<O, RoutingStepRecord> childPath, InverseForeignKey<O, RoutingStepRecord> parentPath) {
        super(path, childPath, parentPath, ROUTING_STEP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoutingStepPath extends RoutingStep implements Path<RoutingStepRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoutingStepPath(Table<O> path, ForeignKey<O, RoutingStepRecord> childPath, InverseForeignKey<O, RoutingStepRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoutingStepPath(Name alias, Table<RoutingStepRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoutingStepPath as(String alias) {
            return new RoutingStepPath(DSL.name(alias), this);
        }

        @Override
        public RoutingStepPath as(Name alias) {
            return new RoutingStepPath(alias, this);
        }

        @Override
        public RoutingStepPath as(Table<?> alias) {
            return new RoutingStepPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RoutingStepRecord, Long> getIdentity() {
        return (Identity<RoutingStepRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoutingStepRecord> getPrimaryKey() {
        return Keys.ROUTING_STEP_PKEY;
    }

    @Override
    public List<ForeignKey<RoutingStepRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROUTING_STEP__FKS0344EWKFFWRBCEMENEEGEB9U);
    }

    private transient RoutingPath _routing;

    /**
     * Get the implicit join path to the <code>public.routing</code> table.
     */
    public RoutingPath routing() {
        if (_routing == null)
            _routing = new RoutingPath(this, Keys.ROUTING_STEP__FKS0344EWKFFWRBCEMENEEGEB9U, null);

        return _routing;
    }

    @Override
    public RoutingStep as(String alias) {
        return new RoutingStep(DSL.name(alias), this);
    }

    @Override
    public RoutingStep as(Name alias) {
        return new RoutingStep(alias, this);
    }

    @Override
    public RoutingStep as(Table<?> alias) {
        return new RoutingStep(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutingStep rename(String name) {
        return new RoutingStep(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutingStep rename(Name name) {
        return new RoutingStep(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutingStep rename(Table<?> name) {
        return new RoutingStep(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep where(Condition condition) {
        return new RoutingStep(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoutingStep where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoutingStep where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoutingStep where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoutingStep where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoutingStep whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
