/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Employee.EmployeePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.Partner.PartnerPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.Quote.QuotePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrderLine.SalesOrderLinePath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrder extends TableImpl<SalesOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sales_order</code>
     */
    public static final SalesOrder SALES_ORDER = new SalesOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesOrderRecord> getRecordType() {
        return SalesOrderRecord.class;
    }

    /**
     * The column <code>public.sales_order.id</code>.
     */
    public final TableField<SalesOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sales_order.delivery_date</code>.
     */
    public final TableField<SalesOrderRecord, LocalDate> DELIVERY_DATE = createField(DSL.name("delivery_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.sales_order.order_date</code>.
     */
    public final TableField<SalesOrderRecord, LocalDate> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.sales_order.order_number</code>.
     */
    public final TableField<SalesOrderRecord, String> ORDER_NUMBER = createField(DSL.name("order_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.sales_order.remarks</code>.
     */
    public final TableField<SalesOrderRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.sales_order.status_code</code>.
     */
    public final TableField<SalesOrderRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.sales_order.employee_id</code>.
     */
    public final TableField<SalesOrderRecord, Long> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sales_order.partner_id</code>.
     */
    public final TableField<SalesOrderRecord, Long> PARTNER_ID = createField(DSL.name("partner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sales_order.quote_id</code>.
     */
    public final TableField<SalesOrderRecord, Long> QUOTE_ID = createField(DSL.name("quote_id"), SQLDataType.BIGINT, this, "");

    private SalesOrder(Name alias, Table<SalesOrderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SalesOrder(Name alias, Table<SalesOrderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sales_order</code> table reference
     */
    public SalesOrder(String alias) {
        this(DSL.name(alias), SALES_ORDER);
    }

    /**
     * Create an aliased <code>public.sales_order</code> table reference
     */
    public SalesOrder(Name alias) {
        this(alias, SALES_ORDER);
    }

    /**
     * Create a <code>public.sales_order</code> table reference
     */
    public SalesOrder() {
        this(DSL.name("sales_order"), null);
    }

    public <O extends Record> SalesOrder(Table<O> path, ForeignKey<O, SalesOrderRecord> childPath, InverseForeignKey<O, SalesOrderRecord> parentPath) {
        super(path, childPath, parentPath, SALES_ORDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SalesOrderPath extends SalesOrder implements Path<SalesOrderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SalesOrderPath(Table<O> path, ForeignKey<O, SalesOrderRecord> childPath, InverseForeignKey<O, SalesOrderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SalesOrderPath(Name alias, Table<SalesOrderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SalesOrderPath as(String alias) {
            return new SalesOrderPath(DSL.name(alias), this);
        }

        @Override
        public SalesOrderPath as(Name alias) {
            return new SalesOrderPath(alias, this);
        }

        @Override
        public SalesOrderPath as(Table<?> alias) {
            return new SalesOrderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SalesOrderRecord, Long> getIdentity() {
        return (Identity<SalesOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesOrderRecord> getPrimaryKey() {
        return Keys.SALES_ORDER_PKEY;
    }

    @Override
    public List<UniqueKey<SalesOrderRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UKITDRI3LNOQU7YV0W5LYUC5TOS);
    }

    @Override
    public List<ForeignKey<SalesOrderRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SALES_ORDER__FK8P31F0RWK0HB56I1K9XOSL2VY, Keys.SALES_ORDER__FKLBFR3ECCAMEAMC9LWELBG7U7L, Keys.SALES_ORDER__FKP3PUH9SDRFN03H5Q818MM5VH0);
    }

    private transient QuotePath _quote;

    /**
     * Get the implicit join path to the <code>public.quote</code> table.
     */
    public QuotePath quote() {
        if (_quote == null)
            _quote = new QuotePath(this, Keys.SALES_ORDER__FK8P31F0RWK0HB56I1K9XOSL2VY, null);

        return _quote;
    }

    private transient EmployeePath _employee;

    /**
     * Get the implicit join path to the <code>public.employee</code> table.
     */
    public EmployeePath employee() {
        if (_employee == null)
            _employee = new EmployeePath(this, Keys.SALES_ORDER__FKLBFR3ECCAMEAMC9LWELBG7U7L, null);

        return _employee;
    }

    private transient PartnerPath _partner;

    /**
     * Get the implicit join path to the <code>public.partner</code> table.
     */
    public PartnerPath partner() {
        if (_partner == null)
            _partner = new PartnerPath(this, Keys.SALES_ORDER__FKP3PUH9SDRFN03H5Q818MM5VH0, null);

        return _partner;
    }

    private transient SalesOrderLinePath _salesOrderLine;

    /**
     * Get the implicit to-many join path to the
     * <code>public.sales_order_line</code> table
     */
    public SalesOrderLinePath salesOrderLine() {
        if (_salesOrderLine == null)
            _salesOrderLine = new SalesOrderLinePath(this, null, Keys.SALES_ORDER_LINE__FK3HHRMXPWT1CQLNXMTIWPY9WPG.getInverseKey());

        return _salesOrderLine;
    }

    @Override
    public SalesOrder as(String alias) {
        return new SalesOrder(DSL.name(alias), this);
    }

    @Override
    public SalesOrder as(Name alias) {
        return new SalesOrder(alias, this);
    }

    @Override
    public SalesOrder as(Table<?> alias) {
        return new SalesOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrder rename(String name) {
        return new SalesOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrder rename(Name name) {
        return new SalesOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrder rename(Table<?> name) {
        return new SalesOrder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder where(Condition condition) {
        return new SalesOrder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
