/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Item.ItemPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.SalesOrder.SalesOrderPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.SalesOrderLineRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderLine extends TableImpl<SalesOrderLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sales_order_line</code>
     */
    public static final SalesOrderLine SALES_ORDER_LINE = new SalesOrderLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesOrderLineRecord> getRecordType() {
        return SalesOrderLineRecord.class;
    }

    /**
     * The column <code>public.sales_order_line.id</code>.
     */
    public final TableField<SalesOrderLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sales_order_line.amount</code>.
     */
    public final TableField<SalesOrderLineRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.sales_order_line.delivery_request_date</code>.
     */
    public final TableField<SalesOrderLineRecord, LocalDate> DELIVERY_REQUEST_DATE = createField(DSL.name("delivery_request_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.sales_order_line.quantity</code>.
     */
    public final TableField<SalesOrderLineRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.sales_order_line.remarks</code>.
     */
    public final TableField<SalesOrderLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.sales_order_line.sort_order</code>.
     */
    public final TableField<SalesOrderLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sales_order_line.unit_price</code>.
     */
    public final TableField<SalesOrderLineRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.sales_order_line.item_id</code>.
     */
    public final TableField<SalesOrderLineRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sales_order_line.sales_order_id</code>.
     */
    public final TableField<SalesOrderLineRecord, Long> SALES_ORDER_ID = createField(DSL.name("sales_order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private SalesOrderLine(Name alias, Table<SalesOrderLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SalesOrderLine(Name alias, Table<SalesOrderLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sales_order_line</code> table reference
     */
    public SalesOrderLine(String alias) {
        this(DSL.name(alias), SALES_ORDER_LINE);
    }

    /**
     * Create an aliased <code>public.sales_order_line</code> table reference
     */
    public SalesOrderLine(Name alias) {
        this(alias, SALES_ORDER_LINE);
    }

    /**
     * Create a <code>public.sales_order_line</code> table reference
     */
    public SalesOrderLine() {
        this(DSL.name("sales_order_line"), null);
    }

    public <O extends Record> SalesOrderLine(Table<O> path, ForeignKey<O, SalesOrderLineRecord> childPath, InverseForeignKey<O, SalesOrderLineRecord> parentPath) {
        super(path, childPath, parentPath, SALES_ORDER_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SalesOrderLinePath extends SalesOrderLine implements Path<SalesOrderLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SalesOrderLinePath(Table<O> path, ForeignKey<O, SalesOrderLineRecord> childPath, InverseForeignKey<O, SalesOrderLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SalesOrderLinePath(Name alias, Table<SalesOrderLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SalesOrderLinePath as(String alias) {
            return new SalesOrderLinePath(DSL.name(alias), this);
        }

        @Override
        public SalesOrderLinePath as(Name alias) {
            return new SalesOrderLinePath(alias, this);
        }

        @Override
        public SalesOrderLinePath as(Table<?> alias) {
            return new SalesOrderLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SalesOrderLineRecord, Long> getIdentity() {
        return (Identity<SalesOrderLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesOrderLineRecord> getPrimaryKey() {
        return Keys.SALES_ORDER_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<SalesOrderLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SALES_ORDER_LINE__FK3HHRMXPWT1CQLNXMTIWPY9WPG, Keys.SALES_ORDER_LINE__FKSX78NRSMY3OC216VK4KTMY1L9);
    }

    private transient SalesOrderPath _salesOrder;

    /**
     * Get the implicit join path to the <code>public.sales_order</code> table.
     */
    public SalesOrderPath salesOrder() {
        if (_salesOrder == null)
            _salesOrder = new SalesOrderPath(this, Keys.SALES_ORDER_LINE__FK3HHRMXPWT1CQLNXMTIWPY9WPG, null);

        return _salesOrder;
    }

    private transient ItemPath _item;

    /**
     * Get the implicit join path to the <code>public.item</code> table.
     */
    public ItemPath item() {
        if (_item == null)
            _item = new ItemPath(this, Keys.SALES_ORDER_LINE__FKSX78NRSMY3OC216VK4KTMY1L9, null);

        return _item;
    }

    @Override
    public SalesOrderLine as(String alias) {
        return new SalesOrderLine(DSL.name(alias), this);
    }

    @Override
    public SalesOrderLine as(Name alias) {
        return new SalesOrderLine(alias, this);
    }

    @Override
    public SalesOrderLine as(Table<?> alias) {
        return new SalesOrderLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderLine rename(String name) {
        return new SalesOrderLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderLine rename(Name name) {
        return new SalesOrderLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderLine rename(Table<?> name) {
        return new SalesOrderLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine where(Condition condition) {
        return new SalesOrderLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
