/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.Shipment.ShipmentPath;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.ShipmentLineRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShipmentLine extends TableImpl<ShipmentLineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shipment_line</code>
     */
    public static final ShipmentLine SHIPMENT_LINE = new ShipmentLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShipmentLineRecord> getRecordType() {
        return ShipmentLineRecord.class;
    }

    /**
     * The column <code>public.shipment_line.actual_amount</code>.
     */
    public final TableField<ShipmentLineRecord, BigDecimal> ACTUAL_AMOUNT = createField(DSL.name("actual_amount"), SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>public.shipment_line.actual_quantity</code>.
     */
    public final TableField<ShipmentLineRecord, BigDecimal> ACTUAL_QUANTITY = createField(DSL.name("actual_quantity"), SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>public.shipment_line.planned_amount</code>.
     */
    public final TableField<ShipmentLineRecord, BigDecimal> PLANNED_AMOUNT = createField(DSL.name("planned_amount"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.planned_quantity</code>.
     */
    public final TableField<ShipmentLineRecord, BigDecimal> PLANNED_QUANTITY = createField(DSL.name("planned_quantity"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.sort_order</code>.
     */
    public final TableField<ShipmentLineRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.unit_price</code>.
     */
    public final TableField<ShipmentLineRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.id</code>.
     */
    public final TableField<ShipmentLineRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.shipment_line.item_id</code>.
     */
    public final TableField<ShipmentLineRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.sales_order_line_id</code>.
     */
    public final TableField<ShipmentLineRecord, Long> SALES_ORDER_LINE_ID = createField(DSL.name("sales_order_line_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.shipment_id</code>.
     */
    public final TableField<ShipmentLineRecord, Long> SHIPMENT_ID = createField(DSL.name("shipment_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.shipment_line.remarks</code>.
     */
    public final TableField<ShipmentLineRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(200), this, "");

    private ShipmentLine(Name alias, Table<ShipmentLineRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShipmentLine(Name alias, Table<ShipmentLineRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shipment_line</code> table reference
     */
    public ShipmentLine(String alias) {
        this(DSL.name(alias), SHIPMENT_LINE);
    }

    /**
     * Create an aliased <code>public.shipment_line</code> table reference
     */
    public ShipmentLine(Name alias) {
        this(alias, SHIPMENT_LINE);
    }

    /**
     * Create a <code>public.shipment_line</code> table reference
     */
    public ShipmentLine() {
        this(DSL.name("shipment_line"), null);
    }

    public <O extends Record> ShipmentLine(Table<O> path, ForeignKey<O, ShipmentLineRecord> childPath, InverseForeignKey<O, ShipmentLineRecord> parentPath) {
        super(path, childPath, parentPath, SHIPMENT_LINE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShipmentLinePath extends ShipmentLine implements Path<ShipmentLineRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShipmentLinePath(Table<O> path, ForeignKey<O, ShipmentLineRecord> childPath, InverseForeignKey<O, ShipmentLineRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShipmentLinePath(Name alias, Table<ShipmentLineRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShipmentLinePath as(String alias) {
            return new ShipmentLinePath(DSL.name(alias), this);
        }

        @Override
        public ShipmentLinePath as(Name alias) {
            return new ShipmentLinePath(alias, this);
        }

        @Override
        public ShipmentLinePath as(Table<?> alias) {
            return new ShipmentLinePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ShipmentLineRecord, Long> getIdentity() {
        return (Identity<ShipmentLineRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShipmentLineRecord> getPrimaryKey() {
        return Keys.SHIPMENT_LINE_PKEY;
    }

    @Override
    public List<ForeignKey<ShipmentLineRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHIPMENT_LINE__FKCKPH63TMH3WUPC5T2IBCTB5OM);
    }

    private transient ShipmentPath _shipment;

    /**
     * Get the implicit join path to the <code>public.shipment</code> table.
     */
    public ShipmentPath shipment() {
        if (_shipment == null)
            _shipment = new ShipmentPath(this, Keys.SHIPMENT_LINE__FKCKPH63TMH3WUPC5T2IBCTB5OM, null);

        return _shipment;
    }

    @Override
    public ShipmentLine as(String alias) {
        return new ShipmentLine(DSL.name(alias), this);
    }

    @Override
    public ShipmentLine as(Name alias) {
        return new ShipmentLine(alias, this);
    }

    @Override
    public ShipmentLine as(Table<?> alias) {
        return new ShipmentLine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShipmentLine rename(String name) {
        return new ShipmentLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShipmentLine rename(Name name) {
        return new ShipmentLine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShipmentLine rename(Table<?> name) {
        return new ShipmentLine(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine where(Condition condition) {
        return new ShipmentLine(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShipmentLine where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShipmentLine where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShipmentLine where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShipmentLine where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShipmentLine whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
