/*
 * This file is generated by jOOQ.
 */
package com.github.gwiman.mini_mes_backend.jooq.tables;


import com.github.gwiman.mini_mes_backend.jooq.Keys;
import com.github.gwiman.mini_mes_backend.jooq.Public;
import com.github.gwiman.mini_mes_backend.jooq.tables.records.WarehouseRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Warehouse extends TableImpl<WarehouseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.warehouse</code>
     */
    public static final Warehouse WAREHOUSE = new Warehouse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WarehouseRecord> getRecordType() {
        return WarehouseRecord.class;
    }

    /**
     * The column <code>public.warehouse.sort_order</code>.
     */
    public final TableField<WarehouseRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.warehouse.use_yn</code>.
     */
    public final TableField<WarehouseRecord, Boolean> USE_YN = createField(DSL.name("use_yn"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.warehouse.created_at</code>.
     */
    public final TableField<WarehouseRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.warehouse.id</code>.
     */
    public final TableField<WarehouseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.warehouse.updated_at</code>.
     */
    public final TableField<WarehouseRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.warehouse.version</code>.
     */
    public final TableField<WarehouseRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.warehouse.warehouse_type_code</code>.
     */
    public final TableField<WarehouseRecord, String> WAREHOUSE_TYPE_CODE = createField(DSL.name("warehouse_type_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.warehouse.code</code>.
     */
    public final TableField<WarehouseRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.warehouse.created_by</code>.
     */
    public final TableField<WarehouseRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.warehouse.updated_by</code>.
     */
    public final TableField<WarehouseRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.warehouse.name</code>.
     */
    public final TableField<WarehouseRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.warehouse.description</code>.
     */
    public final TableField<WarehouseRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(200), this, "");

    private Warehouse(Name alias, Table<WarehouseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Warehouse(Name alias, Table<WarehouseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.warehouse</code> table reference
     */
    public Warehouse(String alias) {
        this(DSL.name(alias), WAREHOUSE);
    }

    /**
     * Create an aliased <code>public.warehouse</code> table reference
     */
    public Warehouse(Name alias) {
        this(alias, WAREHOUSE);
    }

    /**
     * Create a <code>public.warehouse</code> table reference
     */
    public Warehouse() {
        this(DSL.name("warehouse"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<WarehouseRecord, Long> getIdentity() {
        return (Identity<WarehouseRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WarehouseRecord> getPrimaryKey() {
        return Keys.WAREHOUSE_PKEY;
    }

    @Override
    public List<UniqueKey<WarehouseRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.WAREHOUSE_CODE_KEY);
    }

    @Override
    public Warehouse as(String alias) {
        return new Warehouse(DSL.name(alias), this);
    }

    @Override
    public Warehouse as(Name alias) {
        return new Warehouse(alias, this);
    }

    @Override
    public Warehouse as(Table<?> alias) {
        return new Warehouse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(String name) {
        return new Warehouse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(Name name) {
        return new Warehouse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(Table<?> name) {
        return new Warehouse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Condition condition) {
        return new Warehouse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
